### ISSUE TITLE
windows + atomics

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#1]
@saghul brought up that quickjs currently doesn't compile with msvc unless you cut out atomics.

My hunch is that this can be fixed by:

- targeting VS 2022 for proper C11 support, and

- switching to C11 for `<stdatomic.h>`, and

- replacing the pthreads stuff with their standard counterparts from `<threads.h>`

**Comment by saghul** [comment]
Ignoring atomics for now, WDYT about going the `clang-cl` route on native (non MinGW) Windows?

**Comment by bnoordhuis** [comment]
Yes, good idea.

**Comment by xland** [comment]
Many Windows applications are developed based on VisualStudio.
It would be great if quickjs-ng could be compiled by VisualStudio.
Will quickjs-ng 0.2.0  support this feature?

**Comment by saghul** [comment]
Not sure if 0.2.0 but yes, I intend to work on it.

**Comment by xland** [comment]
Test quickjs 0.2.0 with VisualStudio 2022.
Can not build yet.
Waiting...

**Comment by saghul** [comment]
I added ClangCL support on 0.2.0 and since it's ABI compatible with MSVC you should be able to mix them up, but more work is needed for full MSVC compatibility.

**Comment by xland** [comment]
I created the Visual Studio project with CMake GUI.
This project compiled `qjs` with 1798 errors.
Is there another way to compile the source code.
by the way, maybe it's time to write some documentation.

**Comment by saghul** [comment]
I don't know about CMake GUI, but ClamgCL can compile it, albeit with warnings.

New docs will be Coming Soon (TM).

**Comment by to-pse** [comment]
...could anyone clarify if it is now possible to build on Visual Studio?

**Comment by saghul** [comment]
Yes, it is supported by the CMake file and we run multiple jobs in the CI.
