### ISSUE TITLE
Add QuickJS-NG to jsvu

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#113]
Action items from https://github.com/GoogleChromeLabs/jsvu/issues/141:

1. provide binaries at a stable location for:
  - i686 and x86_64 windows
  - i686 and x86_64 linux
  - arm64 macos

2. provide at a stable location a LATEST.json with `{"version":"x.y.z"}`

3. PR jsvu

stable location = GH releases

**Comment by saghul** [comment]
Fat macOS binaries?

**Comment by saghul** [comment]
I can start working on this.

**Comment by bnoordhuis** [comment]
> Fat macOS binaries?

For both x86_64 and arm64, you mean? If at all possible: yes, please.

> I can start working on this.

Also: yes, please :-)

**Comment by saghul** [comment]
On it! I hope to make progress tonight.

**Comment by saghul** [comment]
I created https://github.com/quickjs-ng/quickjs/pull/121 which builds the following binaries:

- Linux: statically linked (musl) x86 and x86_64 
- Windows (MinGW): statically linked x86 and x86_64
- macOS: fat executable with x86_64 and arm64

The next step will be to create a release when a tag is pushed and then create a GH release and upload said artifacts.

Once that is inplace, do we want to make our first release? Exciting times!

**Comment by saghul** [comment]
PR: https://github.com/GoogleChromeLabs/jsvu/pull/142

**Comment by saghul** [comment]
PR landed!
