### ISSUE TITLE
Optimization: Add support for Poly IC

### ISSUE THREAD

**Issue by ammarahm-ed** [quickjs-ng/quickjs#116]
There are different forks of quickjs that implement bits and pieces of really awesome things around QuickJS. One such effort by @openwebf team implements support for Poly IC in quickjs which results in some significant improvement in performance by up to 40%. 

https://github.com/openwebf/quickjs

And even a patch shared on freelists devel: https://www.freelists.org/post/quickjs-devel/Support-Poly-Inline-Cache-in-Get-and-Set-Property

Any thoughts about whether this could be something that is added here in future too?

**Comment by littledivy** [comment]
Aha coincidence! I was just trying out that patch with quickjs-ng

**Comment by ammarahm-ed** [comment]
You might want to try the code in the repo rather than the freelist one since it was updated with some fixes. The perf difference is day and night btw.

**Comment by ammarahm-ed** [comment]
I did face some issues with the fork: more details in this issue with an example to reproduce the bug that occurs with compiled bytecode. https://github.com/openwebf/quickjs/issues/53

**Comment by saghul** [comment]
I see they de-amalgamated QuickJS, which is something I wanted to do, but it complicates integrating other patches...

**Comment by ammarahm-ed** [comment]
Yeah you are right about that. Each file corresponds to a section of code in the `quickjs.c` file so it's still possible to patch it where needed. 

However I actually prefer a single quickjs.c file, it's easier to compile and setup anywhere with simple build steps. Breaking down the code kind of complicates the build process. There's probably a good reason Bellard put everything in a single file haha.

**Comment by littledivy** [comment]
Managed to condese most of the early patches into https://github.com/quickjs-ng/quickjs/pull/120

It does crash when running test262 (probably a silly copy pasta error though)

**Comment by ammarahm-ed** [comment]
> Managed to condese most of the early patches into https://github.com/quickjs-ng/quickjs/pull/120
> 
> It does crash when running test262 (probably a silly copy pasta error though)

That was quick! 🙏
