### ISSUE TITLE
Node API Bindings

### ISSUE THREAD

**Issue by ammarahm-ed** [quickjs-ng/quickjs#118]
Having [NAPI](https://nodejs.org/api/n-api.html) bindings for QuickJS will unlock a lot of NodeJS/Deno modules like napi-rs, [node-ffi-napi](https://www.npmjs.com/package/ffi-napi)  & more to just work drop in without any extra effort. There already exist a couple of efforts to reach this goal in the community.

Almost 100% complete NAPI bindings for QuickJS that work via an abstract NativeEngine implementation. I used a stripped down version of this in a local fun project and got quite farther than I expected after fixing some small bugs:
https://github.com/openharmony/ace_napi/tree/master/native_engine/impl/quickjs

Incomplete but low level NAPI bindings in C that have the basics setup, could be a start for complete napi bindings in C with no overhead:
https://github.com/OrangeLab/Hummer-Virtual-JS-Engine/blob/main/src/js_native_api_qjs.c

**Comment by saghul** [comment]
That can be an ancillary library to QuickJS can't it?

If there is interest it could be maintained in this org.

**Comment by ammarahm-ed** [comment]
Yes, I think you are right. I could be a separate library indeed. It would make more sense to have it in txiki.js would match what node/deno/bun are like. They have it built in.

**Comment by saghul** [comment]
Closing since would need to happen in a separate project / repo.
