### ISSUE TITLE
Fix / drop byte swapped output

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#125]
https://github.com/quickjs-ng/quickjs/blob/463df3adf62ba41c76cc01ede22745f555860a8b/quickjs.c#L32346

The Frida folks seem to have fixed it here: https://github.com/frida/quickjs/commit/f67fb619ecfd601de3385cadf17883624b1538a3

Question: does it make sense to support it or should me make sure we can read bytecode egenrated in a LE machine on a BE one instead?

**Comment by bnoordhuis** [comment]
It's my understanding byte-swapping in general is already implemented. That patch also implements it for regexp bytecode? Can you even write out a regexp today?

General observation: it seems easier to simply always write out LE bytecode and only do byte-swaps when reading it back on a BE machine. Then users never have to even think about byte order, pass the right flags, etc.; it'll just work everywhere.

**Comment by saghul** [comment]
> It's my understanding byte-swapping in general is already implemented. That patch also implements it for regexp bytecode? Can you even write out a regexp today?

With JS_WriteObject I guess?

> General observation: it seems easier to simply always write out LE bytecode and only do byte-swaps when reading it back on a BE machine. Then users never have to even think about byte order, pass the right flags, etc.; it'll just work everywhere.

That was my thinking too.

**Comment by bnoordhuis** [comment]
> With JS_WriteObject I guess?

I just tested but neither it or JS_WriteObjectRec handle JS_CLASS_REGEXP objects. With this diff the bjson test throws an "unsupported object class" error:
```diff
diff --git a/tests/test_bjson.js b/tests/test_bjson.js
index 9b2f44f..6c46ff9 100644
--- a/tests/test_bjson.js
+++ b/tests/test_bjson.js
@@ -160,6 +160,8 @@ function bjson_test_all()
     bjson_test(new Int32Array([123123, 222111, -32222]));
     bjson_test(new Float64Array([123123, 222111.5]));
 
+    bjson_test(/xyzzy/);
+
     /* tested with a circular reference */
     obj = {};
     obj.x = obj;
```
Result:
```
TypeError: unsupported object class
    at write (native)
    at bjson_test (tests/test_bjson.js:104)
    at bjson_test_all (tests/test_bjson.js:163)
    at <anonymous> (tests/test_bjson.js:178)
```

**Comment by saghul** [comment]
Well, that's odd. It would seem like they added support for writing regex objects, but only if byte swapped?!

**Comment by saghul** [comment]
Fixed in https://github.com/quickjs-ng/quickjs/pull/152
