### ISSUE TITLE
RFC: source layout change?

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#133]
Proposal:

src/ almost everything
include/ quickjs.h

Reasoning: I broke embedding in CMake projects because I made the include paths private to avoid a weird CMake error (now fixed). It feels more natural to not jumop through hoops and use a "better" layout.

Bonus: the GH UI looks better since our README would actually be seen :-P

**Comment by bnoordhuis** [comment]
I kind of like flat layouts but no strong disagreement. If it makes things better, go for it.

**Comment by saghul** [comment]
Maybe if / when we add Meson or another build system things become more obvious. As it stands it Just Works (TM).

**Comment by littledivy** [comment]
I really like the single file flat layout :)

**Comment by saghul** [comment]
It would remain a single file, just on src/ with the rest of the files, except the header files which would go on include/

**Comment by bnoordhuis** [comment]
> except the header files which would go on include/

Plural or singular? quickjs.h is the only header file that's intended for public consumption; cutils.h, libbf.h, etc. should probably go into src/.

**Comment by saghul** [comment]
Singlular. Only quickjs.h would go in there. Maybe quickjs-libc.h too since we conditionally export it too...

**Comment by andy0130tw** [comment]
Just in case anyone is interested in building QuickJS with Meson, I have made a fork that roughly translate the original Makefile to Meson build scripts: https://gitlab.com/qbane/quickjs/-/tree/replace-makefile-with-meson.

For more detail, I shared it on the mailing list last month: https://www.freelists.org/post/quickjs-devel/Build-QuickJS-with-Meson-build-system.

**Comment by saghul** [comment]
Cool! I think @bnoordhuis showed interest in having it. Would you like to send it as a PR?

**Comment by andy0130tw** [comment]
Sure! Since my work is modeled after the original Makefile, I need some time to digest the brand new CMake build script.

**Comment by saghul** [comment]
Back on topic: source layout change. I have changed by stance on this. There is value in keeping things as they were, at least for the time being, if only so the transition is smooth, specially for those who were just copying the files over and integrating them in a larger project.
