### ISSUE TITLE
Add `Error.prepareStackTrace` support

### ISSUE THREAD

**Issue by TooTallNate** [quickjs-ng/quickjs#134]
To enable support for stack traces within applications using QuickJS, it would be ideal to support some form of the non-standard `Error.prepareStackTrace` API.

I have a fork of QuickJS where I am using this, you can re-use the implementation from there if desired: https://github.com/TooTallNate/quickjs/commit/29339cc8c4bb4867a8798b0575f42964dcda30f9

**Comment by saghul** [comment]
Yep I'd like us to have it. The Frida fork also has an implementation, I'll take a look and see what the differences are.

While we're at it it would be nice to add sourcemap support to the CLI :-)

**Comment by saghul** [comment]
The Frida implementation: https://github.com/frida/quickjs/commit/78fd25fed8fd0a2903f6038ab10bbae71ff968b4

**Comment by bnoordhuis** [comment]
Relevant implementation detail: V8 passes in a list of `CallSite` objects with the following methods:
```
getColumnNumber
getEnclosingColumnNumber
getEnclosingLineNumber
getEvalOrigin
getFileName
getFunction
getFunctionName
getLineNumber
getMethodName
getPosition
getPromiseIndex
getScriptNameOrSourceURL
getThis
getTypeName
isAsync
isConstructor
isEval
isNative
isPromiseAll
isToplevel
```

**Comment by saghul** [comment]
https://v8.dev/docs/stack-trace-api

**Comment by TooTallNate** [comment]
Also somewhat related to this, is QuickJS's stack traces seem to not include column number information, which makes resolving source maps of minified files basically useless. Would be nice to rectify that, but I had no idea how to do so when I was digging through the code.

**Comment by bnoordhuis** [comment]
#149 for column numbers. PR welcome if you're up for it :)
