### ISSUE TITLE
Add Promise state inspection APIs

### ISSUE THREAD

**Issue by TooTallNate** [quickjs-ng/quickjs#135]
For debugging and/or inspection style APIs (like `console.log()` formatting), it would be nice to have an API where the internal state of a `Promise` can be introspected.

A potential implementation that can be used is here: https://github.com/TooTallNate/quickjs/commit/bcdd746c19028ea214f85305b1e9ad2e813f755a

**Comment by saghul** [comment]
Hey there!

That should already be there. https://github.com/quickjs-ng/quickjs/blob/7776cc3b75b51ca884f4b50cb060603719849b2c/quickjs.h#L1006

It was part of top level await.

**Comment by TooTallNate** [comment]
Good stuff 👍
