### ISSUE TITLE
Add column numbers to stack traces

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#149]
quickjs currently only records the line number. Also record the column.

Needs (hopefully) minor tweaks to the token parser and the pc2line RLE data structure that's attached to JSFunctionDef and JSFunctionBytecode objects.

Refs: https://github.com/quickjs-ng/quickjs/issues/134#issuecomment-1828386599

**Comment by ammarahm-ed** [comment]
For reference this was previously implemented here https://github.com/openwebf/quickjs/pull/12, https://github.com/openwebf/quickjs/pull/1  and some other PRS for quickjs.

**Comment by ammarahm-ed** [comment]
Here's the related patch submitted on free-lists https://www.freelists.org/post/quickjs-devel/feat-add-the-column-number-feature-of-Error-Object-and-its-stack
