### ISSUE TITLE
Script fails when it uses imports

### ISSUE THREAD

**Issue by sciurius** [quickjs-ng/quickjs#164]
I use a javascript program [abc2svg](https://chiselapp.com/user/moinejf/repository/abc2svg/doc/trunk/README.md) that I call using a wrapper script `chordproabc.js`. This works fine:
````
$ qjs --std chordproabc.js lib/abc2svg foo.html foo.abc
````

However, when I add two import lines
````
import * as std from 'std'
import * as os  from 'os'
````
Now the script fails somewhere in the guts of abc2svg. It doesn't matter whether I import something or everything from std or os, as soon as I have an import it fails.

````
$ qjs --std chordproabc.js lib/abc2svg foo.html foo.abc
TypeError: not a function
    at abc_cmd (lib/abc2svg/cmdline.js:148)
    at <anonymous> (chordproabc.js:77)
````

I don't have a clue what is going on. I want to use the script from an embedded QuickJS [JavaScript::QuickJS](https://github.com/FGasper/p5-JavaScript-QuickJS) that does not have the equivalent of `--std` so I need the imports.

I've attached a zip with the necessary files to reproduce this.
[qq.zip](https://github.com/FGasper/p5-JavaScript-QuickJS/files/13509629/qq.zip)

**Comment by saghul** [comment]
You need to add this to your chodproabc.js:

```
 globalThis.abc2svg = abc2svg;
```

Without the imports it's executed as a script so `var abc2svg` creates a global, not so when using modules.
