### ISSUE TITLE
Flaky test (cygwin)

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#184]
```
build/qjs tests/test_std.js
Error: assertion failed: got |0|, expected |3|
    at assert (tests/test_std.js:20)
    at test_os_exec (tests/test_std.js:249)
    at <anonymous> (tests/test_std.js:270)
```
Which is this line:
```js
assert(status & 0x7f, os.SIGQUIT);
```

**Comment by kapouer** [comment]
I'm seeing that failure on [Hurd](https://buildd.debian.org/status/fetch.php?pkg=quickjs-ng&arch=hurd-amd64&ver=0.14.0-2&stamp=1778920362&raw=0). Not a problem, I can just disable that test too.
However, is it possible that "cat" returns very quickly with status 0 ? In which case we're just seeing a race condition.

**Comment by saghul** [comment]
FWIW I haven't seen that in a really long time.
