### ISSUE TITLE
Drop non-standard features

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#20]
A slight generalization of https://github.com/quickjs-ng/quickjs/issues/17

- BigFloat / BigDecimal
- ✅ use math (then we also drop qjscalc)
- ✅ use strip
- JSON extension?

**Comment by saghul** [comment]
@bnoordhuis Thoughts on the JSON extension?

**Comment by bnoordhuis** [comment]
That's in std, right? I'm personally not bothered by it but I don't object to removing it. For my own projects the quickjs-libc.c stuff is immaterial, I don't use it.

**Comment by saghul** [comment]
std exposes support for it but the actual implementation is in the core.

**Comment by saghul** [comment]
This is done now.

**Comment by bnoordhuis** [comment]
I'm reopening this for a short bit as a reminder because after #34 lands, there is still one non-standard feature left, the BigInt extensions: floorLog, sqrtrem, etc.

**Comment by Sytten** [comment]
The removal of the JSON extended is a bit unfortunate since we had to remove it in rquickjs when we switched over.
