### ISSUE TITLE
Broken JS_READ_OBJ_ROM_DATA flag

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#206]
This `JS_ReadObject()` flag no longer works for bytecode. The IC opcodes introduced in #120 are patched during execution.

I can see a few solutions:

1. disable ICs when the bytecode buffer should be considered immutable

2. make a copy of the bytecode buffer in `JS_ReadFunctionBytecode()`

3. remove the flag

I'm leaning towards option 3 so if anyone is using the flag, now would be a good time to speak up. :-)

**Comment by saghul** [comment]
Agreed with option 3.
