### ISSUE TITLE
expose JS_GetModuleNamespace (or rebase on upstream)

### ISSUE THREAD

**Issue by justjake** [quickjs-ng/quickjs#259]
Upstream decided to expose `JS_GetModuleNamespace` as an API to get the exports of a ESModule, see here:

https://github.com/bellard/quickjs/blob/2c793e50979e64a51178c1048071c97722eb1bf1/quickjs.h#L879

My library supports both upstream and quickjs-ng, so currently I need to patch in JS_GetModuleNamespace in my vendored copy of quickjs-ng

**Comment by saghul** [comment]
We added an equivalente before 😔 https://github.com/quickjs-ng/quickjs/commit/6868fb9e2516fde4a7a3fcef113a6bb1e5ecc957

**Comment by justjake** [comment]
I know you added some custom C APIs for this purpose, but it would be great to pick up the official API from upstream

**Comment by saghul** [comment]
Yep, will do.

**Comment by justjake** [comment]
Thanks
