### ISSUE TITLE
RFC: check-in repl.c and friends

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#262]
I was about to embark on forward-porting my WASI patches, but I realized that due to the codegen step, the build becomes quite complex. In fact I don't know how to solve that...

The same thing applies to cross-compiling for MinGW for example.

It would greatly simplify cross-compiling if we checked the C files in. Since there is no bytecode incompatibility shenanigans now, it should be safe to do.

Thoughts?

/cc @bnoordhuis

**Comment by bnoordhuis** [comment]
As long as it doesn't change too often and doesn't get out of sync with repl.js, I'm okay with that.

**Comment by saghul** [comment]
I generqally doesn't, and I could automate a check in GHA by regenerating it and checking if there is a diff.

**Comment by chqrlie** [comment]
Would you move these files to a subdirectory?  Do they get rebuilt if the JavaScript source file changes?

**Comment by saghul** [comment]
They are not regenerated automatically, `make codegen` does it, but the CI checks if they are out of sync and will fail, so there is that safety net.

Any suggestion for the generated directory?

**Comment by chqrlie** [comment]
I guess we cannot use `codegen` as it would conflict with the make target, how about `gen` ?

**Comment by saghul** [comment]
Sounds good!
