### ISSUE TITLE
Rounding bug on Windows (MinGW)

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#27]
Someone reported it on txiki.js, but I just ran into it while adding a MinGW CI in https://github.com/quickjs-ng/quickjs/pull/24

```
./qjs tests/test_builtin.js
Error: assertion failed: got |2e+1|, expected |3e+1|
    at assert (tests/test_builtin.js:17)
    at test_number (tests/test_builtin.js:343)
    at <eval> (tests/test_builtin.js:680)
# That is:
assert.eq((25).toExponential(0), "3e+1");
```

Turns out `(25).toExponential(0)` on mingw is  `2e+1`.

txiki.js bug: https://github.com/saghul/txiki.js/pull/401 - The original reporter mentioned llvm-mingw, but I'm only adding the gcc based environments to CI for now.

**Comment by bnoordhuis** [comment]
> Turns out `(25).toExponential(0)` on mingw is `2e+1`

Observation: 25 in exponential notation is 2.5e+1 and because the `digits` argument is zero it's supposed to be rounded up to 3e+1. However...

https://github.com/quickjs-ng/quickjs/blob/2f51cbc4e676d54115b4d803028d675463d8791c/quickjs.c#L65-L68

Let me try if enabling CONFIG_PRINTF_RNDN for mingw fixes the issue.

**Comment by FGasper** [comment]
The issue is, I think, fundamental: printf doesn’t necessarily obey fenv’s rounding settings. OpenBSD has this problem as well.

**Comment by saghul** [comment]
@FGasper Looks that way yeah. Do you have a suggestion on how to tackle it?

**Comment by FGasper** [comment]
@saghul Off-hand, all I can think of involves arithmetic, and I don’t know binary64 well enough to know when that might or might not entail potential rounding errors. I’m looking, though … interesting problem!

**Comment by bnoordhuis** [comment]
I'm closing this as a special case of #242.
