### ISSUE TITLE
Commit 48e4c63a breaks tcc build

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#270]
At commit 48e4c63a:
```
In file included from run-test262.c:38:
cutils.h:239: error: incompatible types for redefinition of 'PACK'
```
Previous commit builds fine.

**Comment by saghul** [comment]
I can look into adding tcc to the Ci.

**Comment by bnoordhuis** [comment]
I thought about that too but I couldn't decide on what version to target.

I use https://repo.or.cz/w/tinycc.git but they don't do releases, whereas Fabrice's last release (and the version in apt) is from 2017 and lags behind quite a bit.

**Comment by saghul** [comment]
Perhaps we could simply pin a commit from that repo, to make builds consistent / reproducible?

**Comment by bnoordhuis** [comment]
Yes, that's a good idea. FWIW, I'm at commit `81a32ec305ee871d8129978bf3d57bc108bec46b` from December and it seems to work okay. Not saying you should use it but, if you want a data point, now you have one. :-)
