### ISSUE TITLE
Time zone offset for Win32

### ISSUE THREAD

**Issue by afulsamet** [quickjs-ng/quickjs#290]
Patch to get current time zone offset for Win32. [GetTimeZoneInformation](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-gettimezoneinformation): Retrieves the current time zone of the active machine, check [remarks](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-gettimezoneinformation#remarks) to see formula.

> The bias is the difference, in minutes, between UTC time and local time.

```diff
diff --git a/quickjs.c b/quickjs.c
index c6efc21..fadde4a 100644
--- a/quickjs.c
+++ b/quickjs.c
@@ -40827,8 +40827,9 @@ static const JSCFunctionListEntry js_math_obj[] = {
    between UTC time and local time 'd' in minutes */
 static int getTimezoneOffset(int64_t time) {
 #if defined(_WIN32)
-    /* XXX: TODO */
-    return 0;
+    TIME_ZONE_INFORMATION time_zone_info;
+    GetTimeZoneInformation(&time_zone_info);
+    return (int)time_zone_info.Bias / 60;
 #else
     time_t ti;
     struct tm tm;

```

**Comment by saghul** [comment]
Thank you! Do you mind sending it as an actual pull request?

**Comment by afulsamet** [comment]
Yes, here it is: [Implement getTimezoneOffset for Win32 #291](https://github.com/quickjs-ng/quickjs/pull/291) 🎉

**Comment by saghul** [comment]
Merged! 🎉
