### ISSUE TITLE
CI yaml file should be updated

### ISSUE THREAD

**Issue by chqrlie** [quickjs-ng/quickjs#292]
All CI jobs complain about needing an update from node 16 to node 20:

[linux (Debug)](https://github.com/quickjs-ng/quickjs/actions/runs/8131467408/job/22220827194)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Changing `actions/checkout@v3` to `actions/checkout@v4` seems an easy fix, but I am not sure if it will be sufficient.

**Comment by saghul** [comment]
That should indeed be the only change necessary.
