### ISSUE TITLE
Consider running test262

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#3]
There is a builtin runner. Sample run with `make test2-default`

```
151/39546/8859
Average memory statistics for 39546 tests:

QuickJS memory usage -- BigNum 2021-03-27 version, 64-bit, malloc limit: -1

NAME                    COUNT     SIZE
memory allocated          962   117824  (122.5 per block)
memory used               963   109364  (0 overhead, 8.8 average slack)
atoms                     533    21987  (41.3 per atom)
objects                   171    12349  (72.2 per object)
  properties              877    15778  (5.1 per object)
  shapes                   59    13279  (225.1 per shape)
bytecode functions         13     1549
  bytecode                 13      937  (72.1 per function)
C functions                99
arrays                      1
  fast arrays               1
  elements                  1       16  (1.0 per fast array)

Result: 151/39546 errors, 1487 excluded, 8859 skipped, 135 new, 1 changed
       72.82 real        51.04 user         6.82 sys
```

**Comment by bnoordhuis** [comment]
I agree, I have it as a TODO in .github/workflows/ci.yml.

I can set it up but do you agree we don't want to vendor tc39/test262? It's pretty big (about 235 MB) so my current thinking is to git-submodule it. I hate them with a passion but it's the least worst option I can think of.

**Comment by bnoordhuis** [comment]
#11

**Comment by saghul** [comment]
> I agree, I have it as a TODO in .github/workflows/ci.yml.
> 
> 
> 
> I can set it up but do you agree we don't want to vendor tc39/test262? It's pretty big (about 235 MB) so my current thinking is to git-submodule it. I hate them with a passion but it's the least worst option I can think of.

Makes sense! Alternatively we could git clone or plain download it as part of the test process. But a submodule is the simplest for now!
