### ISSUE TITLE
Evaluate expressions in a specific scope

### ISSUE THREAD

**Issue by lindeer** [quickjs-ng/quickjs#312]
I ask the [same question](https://github.com/bellard/quickjs/issues/253) here in case nobody reply it, seems our repo is more active :)

**Comment by bnoordhuis** [comment]
So, I think what you're asking is if you can do this in C?
```js
const o = {a: 42, b: 1337}
with (o) console.log(a + b)
```
quickjs currently doesn't support that through its C API but there's no reason it couldn't. V8 has a similar C++ API, it's not without precedence.

As a workaround, you can wrap the JS code to evaluate in a `with ({ /* ... */ }) { /* ... */ }` block.

**Comment by chqrlie** [comment]
You want to use `o` as the scope object.  I guess you could set `o`'s prototype to the `globalThis` and use an API that uses it as the global object.  I am not sure if this can be done easily with the current API, but it makes sense.

Another approach is to use a different realm and set the properties directly into its global object, but you probably want to use a specific object so not really a generic solution.

I have a similar use case where I would want a script to execute with a stack/list of scope objects. Will investigate.

**Comment by lindeer** [comment]
Great thanks for your nice idea! @bnoordhuis 

My cases are more 'embeded', I may evaluate different expressions at different time. It could be made like this, if anyone meet the same case:
```c
    // define the object you want to run in its scope.
    const char* js_def = "let scope={x:10, y:20, onClick:function() { return this.x*this.y;}};";
    JS_Eval(ctx, js_def, strlen(js_def), "<definition>", JS_EVAL_TYPE_GLOBAL);

    // call it somewhere
    result = my_eval("x+y");
    JS_ToInt32(ctx, &r, result);

    // call somewhere else
    result = my_eval("onClick()");
```
and define the wrapper function `my_eval`:
```c
JSValue my_eval(JSContext *ctx, const char* expr) {
    char buf[200];
    sprintf(buf, "with(scope) {%s}", expr);
    return JS_Eval(ctx, buf, strlen(buf), "<eval>", JS_EVAL_TYPE_GLOBAL);
}
```

**Comment by lindeer** [comment]
thanks @chqrlie , could I have a look at some example code? how could I `set o's prototype to the globalThis` and `uses an API as the global object` ? have no idea...

**Comment by chqrlie** [comment]
> ```c
> JSValue my_eval(JSContext *ctx, const char* expr) {
>     char buf[200];
>     sprintf(buf, "with(scope) {%s}", expr);
>     return JS_Eval(ctx, buf, strlen(buf), "<eval>", JS_EVAL_TYPE_GLOBAL);
> }
> ```

May I suggest a safer alternative:

```
JSValue my_eval(JSContext *ctx, const char* expr) {
    char buf[200];
    int len = snprintf(buf, sizeof buf, "with(scope) {%s}", expr);
    return JS_Eval(ctx, buf, len, "<eval>", JS_EVAL_TYPE_GLOBAL);
}
```
