### ISSUE TITLE
The v8 tests from `test262/implementation-contributed/v8/mjsunit/` are outdated

### ISSUE THREAD

**Issue by chqrlie** [quickjs-ng/quickjs#313]
The v8 test cases in `test262/implementation-contributed/v8/mjsunit/` are outdated. The current version of v8 has different error messages and more test cases.  Of course the error messages are implementation defined so they can change at will...
The v8 tests are useful for conformity because they complement the test262 suite.  We might want to create a repository that loosely tracks the `test/mjsunit` directory of the v8 repository and use that as a submodule.
The reports should also be improved to help track the actual arguments for which the failures occur. `v8-tweak.js` is a good start but more precise output including a full stack dump with line numbers and argument values would definitely help.

**Comment by saghul** [comment]
Closing since they were removed upstream. See: https://github.com/quickjs-ng/quickjs/commit/408fed8fa50613a5e70f06cea25a170bc7cc7b3a
