### ISSUE TITLE
linux-asan and linux-msan CI tests are broken

### ISSUE THREAD

**Issue by chqrlie** [quickjs-ng/quickjs#314]
These tests are broken in CI but seem to run fine locally.

**Comment by bnoordhuis** [comment]
GitHub upgraded the ubuntu-latest images from 20.04 to 22.04 a few days ago. I suspect that's the reason. Let's see if pinning fixes<sup>1</sup> the problems.

<sup>1</sup> "mitigates", really. Not a long-term solution.
