### ISSUE TITLE
Valgrind test takes too long

### ISSUE THREAD

**Issue by chqrlie** [quickjs-ng/quickjs#361]
The valgrind test takes longer than 4 hours and tends to fail for reasons unrelated to code issues:

- test262/test/built-ins/Atomics/notify/notify-all-on-loc.js:13: strict mode: unexpected error: Test262Error: The value of reports[NUMAGENT + 1] is "W timeout after Atomics.notify" Expected SameValue(«W timeout before Atomics.notify», «W timeout after Atomics.notify») to be true
- run gets automatically cancelled after 6 hours.

We should investigate and find a workaround for the `Atomics` test that fails because of the slow execution.

We should disable some of the test262 tests that take too long to bring the time back to less than one hour: the file **test262_report.txt** can help for this as lengthy tests have a `test: xxx ms`.  Without valgrind, more than 450 tests take more than 100ms on my laptop, here is a list of the pathological ones:
```
35: test262/test/annexB/built-ins/RegExp/RegExp-leading-escape-BMP.js time: 327 ms
37: test262/test/annexB/built-ins/RegExp/RegExp-trailing-escape-BMP.js time: 336 ms
4528: test262/test/built-ins/Atomics/notify/notify-in-order-one-time.js time: 658 ms
4529: test262/test/built-ins/Atomics/notify/notify-in-order.js time: 633 ms
4615: test262/test/built-ins/Atomics/wait/bigint/waiterlist-order-of-operations-is-fifo.js time: 625 ms
4665: test262/test/built-ins/Atomics/wait/waiterlist-order-of-operations-is-fifo.js time: 636 ms
12849: test262/test/built-ins/RegExp/CharacterClassEscapes/character-class...   6 tests
13245: test262/test/built-ins/RegExp/character-class-escape-non-whitespace.js time: 229 ms
13348: test262/test/built-ins/RegExp/property-escapes/generated/...  417 tests
24844: test262/test/built-ins/decodeURI...   18 tests
25853: test262/test/language/comments/S7.4_A5.js time: 201 ms
25854: test262/test/language/comments/S7.4_A6.js time: 165 ms
37465: test262/test/language/identifiers/start-unicode-...  12 tests
37970: test262/test/language/literals/regexp/S7.8.5_A1.1_T2.js time: 323 ms
37982: test262/test/language/literals/regexp/S7.8.5_A1.4_T2.js time: 331 ms
37990: test262/test/language/literals/regexp/S7.8.5_A2.1_T2.js time: 353 ms
38000: test262/test/language/literals/regexp/S7.8.5_A2.4_T2.js time: 349 ms
```
Using an extra config file to disable lengthy tests for valgrind would be a good way to solve this issue.

**Comment by saghul** [comment]
> Using an extra config file to disable lengthy tests for valgrind would be a good way to solve this issue.

Agreed!

**Comment by chqrlie** [comment]
> > Using an extra config file to disable lengthy tests for valgrind would be a good way to solve this issue.
> 
> Agreed!

Made a PR #362 to address this issue.  On my laptop:
```
$ time make test262-fast
Result: 12/76219 errors, 2149 excluded, 7767 skipped

real    0m25.820s
user    0m21.776s
sys     0m2.626s

$ make test262
Result: 12/77263 errors, 1627 excluded, 7767 skipped

real    2m31.364s
user    1m52.704s
sys     0m8.893s
```

**Comment by saghul** [comment]
Very useful!

**Comment by chqrlie** [comment]
With this change the valgrind test took 38m 45s !

**Comment by chqrlie** [comment]
PR #362 closed this issue.
