### ISSUE TITLE
[Feature Request] Add `JS_ToBigUint64()` function

### ISSUE THREAD

**Issue by TooTallNate** [quickjs-ng/quickjs#376]
There already exists:

* `JS_ToBigInt64()`
* `JS_NewBigUint64()`
* `JS_NewBigInt64()`

Notably missing from this list is `JS_ToBigUint64()`, which means I have to cast my `uint64_t *` value to `int64_t *` when using the `JS_ToBigInt64()` function. Would be nice to not need to do the casting part, and makes sense to add it for API symmetry IMO.

**Comment by saghul** [comment]
Makes sense!

**Comment by bnoordhuis** [comment]
For anyone wanting to work on this: it should be as easy as replacing bf_get_int64 with bf_get_uint64

**Comment by Troy-Butler** [comment]
Hi, could you please assign this to me?

**Comment by saghul** [comment]
We don't assign issues, feel free to send a PR though!
