### ISSUE TITLE
C++ Macro compatibility

### ISSUE THREAD

**Issue by KaruroChori** [quickjs-ng/quickjs#425]
Following the trail of https://github.com/quickjs-ng/quickjs/pull/422, to improve the wider compatibility with C++ some macros would require minimal rework.

https://github.com/quickjs-ng/quickjs/blob/22c10224ac9885051ada62ac11a1d6e55593042b/quickjs.h#L960C1-L975C145

For reference, an equivalent problem discussed in https://github.com/saghul/txiki.js/issues/535

**Comment by chqrlie** [comment]
This seems a good change.  This allows a C++ module to define an array of properties using these macros without an explicit `extern C++` tag.

**Comment by KaruroChori** [comment]
https://github.com/quickjs-ng/quickjs/pull/428
