### ISSUE TITLE
`-fwrapv` flag needed?

### ISSUE THREAD

**Issue by andrjohns** [quickjs-ng/quickjs#444]
The QuickJS Makefile adds the [`-fwrapv` flag](https://github.com/bellard/quickjs/blob/36911f0d3ab1a4c190a4d5cbe7c2db225a455389/Makefile#L135) for defined-handling of integer overflows, but it's not set in QuickJS-NG. 

Is that because it's not needed here or should it also be used? Just double-checking whether I need to change build flags as part of switching a codebase over to this fork

**Comment by saghul** [comment]
IIRC we fixed the cases that required that flag early in the fork.

**Comment by andrjohns** [comment]
Great, thanks!
