### ISSUE TITLE
Windows character output is garbled

### ISSUE THREAD

**Issue by ahaoboy** [quickjs-ng/quickjs#447]
I'm not sure if it's a qjs encoding problem or a windows setting problem, the output in both windows terminal and vscode terminal is garbled.

```js
console.log('│')

```
 
![image](https://github.com/quickjs-ng/quickjs/assets/19884146/c9a90637-2382-434f-8f70-f762182d86c0)

It is correct to use redirection to write output to a file

```
 ./build/qjs ./a.js > a.txt
```
![image](https://github.com/quickjs-ng/quickjs/assets/19884146/32199f51-cbcd-4791-87a8-ddecc3b1183b)

**Comment by andrjohns** [comment]
The error is happening because the pipe character you've specified is not the standard pipe, it's a different unicode symbol: https://apps.timwhitlock.info/unicode/inspect?s=console.log%28%27%E2%94%82%27%29

Not sure what the spec says about how this should be parsed, @saghul?

**Comment by andrjohns** [comment]
Spoke too soon sorry, it's actually a windows-specific issue with parsing unicode inputs in `js_load_file`

**Comment by ahaoboy** [comment]
This problem seems to have been encountered before, but it has not been solved.
https://github.com/bellard/quickjs/issues/220

**Comment by saghul** [comment]
Fixed in https://github.com/quickjs-ng/quickjs/pull/449
