### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by tim-field** [quickjs-ng/quickjs#467]
Is support for locale [functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) possible or planned?

I see [some tests](https://github.com/quickjs-ng/quickjs/blob/7faef8680dd29abe8c46138c62696a3dc464e2b7/tests/test_builtin.js#L711) that look to provide some support here for Dates at least.  In this case is it possible to provide a different locale from `en` ?

Thanks 🙏

**Comment by tim-field** [comment]
Otherwise has anyone had luck polyfilling these, this seems difficult as polyfills want to attach to `global` but I could well be going about this wrong

**Comment by saghul** [comment]
I think adding full locale functions would involve using something like ICU which is huge, so I don't think that's in the cards.

The support for Date objects refers to timezone data IIRC.

**Comment by tim-field** [comment]
For future travelers, I was able to polyfill using the fastly polyfill service here https://polyfill-fastly.io/

Select all the Intl packages ( also include locales that you need i.e. `Intl.~locale.en` )

Save the result to a file and then module load that into quickjs.
