### ISSUE TITLE
Implement resizable ArrayBuffer

### ISSUE THREAD

**Issue by guest271314** [quickjs-ng/quickjs#477]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resizable

**Comment by saghul** [comment]
Previous attempt: https://github.com/quickjs-ng/quickjs/pull/85

**Comment by guest271314** [comment]
Keep on attempting. It took me 29 different versions to achieve one of my requirements. I put creating Native Messaging hosts using V8's `d8` shell and SpiderMonkey's `js` shell on hold for a year before diving back in, and eventually achieving what I set out to do. 

If Deno, Bun, Node.js, Chromium, and Firefox (late to the party) can do it, so can txiki.js.

**Comment by bnoordhuis** [comment]
I've been looking into this and I just want to note this little facepalm moment. First, observe how we're not allowed to create typed arrays with a backing buffer that's not a multiple of the element size:
```js
var ta = new Uint32Array(new ArrayBuffer(3))
// RangeError: invalid array buffer length
var ta = new Uint32Array(new ArrayBuffer(7))
// ditto
```
Makes sense, right? Okay, so let's create Uint32Array with a properly sized buffer and make it resizable:
```js
var ta = new Uint32Array(new ArrayBuffer(4, {maxByteLength: 4}))
ta[0] = 0x11223344 // make a note of this!
```
Now watch me perform a little magic trick:
```js
ta.buffer.resize(3)
print(ta.length) // prints "0"
print(ta[0]) // prints "undefined"
```
Still making sense so far, kind of anyway. But then:
```js
print(ta.buffer.byteLength) // prints "3" because...
ta.resize(4)
print(ta[0].toString(16)) // prints "223344"
```
Where did 0x11 go? Indeed, gone; replaced by zero - but only on little endian systems; on big endian systems, it prints `112233`!

I could shrug that off as "okay, that's life for the JS engine maintainer" but for extra facepalm, observe how this is legal...
```js
var ta = new Uint32Array(new ArrayBuffer(3, {maxByteLength: 3}))
```
...even though it's _never_ going to produce anything useful. Why is that not a RangeError?!

**Comment by guest271314** [comment]
@bnoordhuis I think you are mixing up `ArrayBuffer` and `TypedArray` interfaces. 

We can write any data we want to an `ArrayBuffer`. 

If we want exacting endianness we can use a `DataView`  to write values.

**Comment by saghul** [comment]
Is that what the spec says or the way V8 behaves? Very strange indeed!

**Comment by guest271314** [comment]
> Is that what the spec says or the way V8 behaves? Very strange indeed!

Firefox Nightly 133 (SpiderMonkey JavaScript/WebAssembly engine) and Bun 1.1.34 (JavaScriptCore JavaScript engine written in Zig) don't throw, so it's not a V8 issue.

**Comment by guest271314** [comment]
Amazon Web Services LLRT does throw

```
llrt -e 'var ta = new Uint32Array(new ArrayBuffer(3, {maxByteLength: 3}))'
RangeError: invalid length
  at Uint32Array (native)
      at <eval> (eval_script:1:10)

```

**Comment by guest271314** [comment]
I suppose it would be interesting to test this in multiple JavaScript engines and runtimes. I'm currently running AWS Labs `llrt`, `qjs` (QuickJS NG), `tjs`, Bun (canary), Deno (canary), Node.js nightly from a couple days ago, Cloudflare Workerd, Bytecode Alliance's Javy (which uses QuickJS under the hood), SerenityOS's LibJS, Meta's `hermes` and `shermes`, SpiderMonkey's `js`, Google V8's `d8`. Workerd probably has this implemented already. The Cap'n Proto configuration is cumbersome, though we could create such a test to see what happens in these engines and runtimes without warning them that their implementations are going to be tested for this, to see what happens.

But then that gets into implementation details. Implementers, in general, do whatever they want, and can massage their own ideology into interpretation of ECMA-262. 

Interesting test case.

**Comment by bnoordhuis** [comment]
> I think you are mixing up ArrayBuffer and TypedArray interfaces

I'm not mixing anything up, I'm showing the (IMO weird!) interaction between the two.

llrt ~~not~~ throwing is no surprise. It's based off bellard/master; it doesn't supports resizable arraybuffers, it ignores the maxByteLength option.

**Comment by guest271314** [comment]
Chromium Version 132.0.6796.0 (Developer Build) (64-bit) doesn't throw.

I've never constructed a resizable `ArrayBuffer` as a parameter to a `TypeArray` constructor in the various ways I've used resizable `ArrayBuffer`. 

It wouldn't really make sense to construct a `Uint32Array` with a source buffer that has a `byteLength` of `3`. Unless that is to test.

I generally construct the resizable `ArrayBuffer` and write to and read from that `ArrayBuffer` using indexes directly, or a `DataView`.

**Comment by guest271314** [comment]
@bnoordhuis I'm curious what you are trying to determine?

**Comment by bnoordhuis** [comment]
It's a spec compliance thing. It doesn't matter if it makes sense to construct a typed array like that, it matters that test262 requires it :-)

After thinking about it, I kind of see the logic. Consider:
```js
var ab = new ArrayBuffer(12, {maxByteLength:12})
var ta = new Uint32Array(ab, 4, 2)
print(ta.byteOffset) // 4
print(ta.byteLength) // 8
print(ta.length) // 2
ab.resize(11)
print(ta.byteOffset) // 0
print(ta.byteLength) // 0
print(ta.length) // 0
ab.resize(8)
print(ta.byteOffset) // 0
print(ta.byteLength) // 0
print(ta.length) // 0
ab.resize(12) // and back again
print(ta.byteOffset) // 4
print(ta.byteLength) // 8
print(ta.length) // 2
```
Shrinking the arraybuffer turns the typed array into a zero-length array, regardless of whether the arraybuffer is a multiple of the typed array's element size.

edit: more formally, the typed array gets neutered when `ta.byteOffset + ta.byteLength > ab.byteLength`

edit2: but only for the 3 arg typed array constructor, `new Uint32Array(ab, byteOffset, count)`; the 2 arg constructor `new Uint32Array(ab, byteOffset)` auto-adjusts its length

**Comment by guest271314** [comment]
TBH I was not thinking about test262 at all. My interest is in runtime agnostic JavaScript, specifically running the same script in multiple JavaScript runtimes. As a contributor here I can see how test262 is a concern of yours.

As an aside I do have an off-topic question about ECMA-262 and a particular implementation by a different runtime that has been nagging me, if you are up to field that question outside of this issue. If not, that's fine, too.

**Comment by bnoordhuis** [comment]
Sure, but can you open a discussion for that?

**Comment by guest271314** [comment]
@bnoordhuis https://github.com/quickjs-ng/quickjs/discussions/629.

**Comment by guest271314** [comment]
@bnoordhuis 

QuickJS built from txiki.js deps, a couple hours ago.

```
git clone --recursive https://github.com/saghul/txiki.js --shallow-submodules && cd txiki.js
make 
cp "$PWD/build/tjs" ~/bin

cd deps/quickjs
make
cp "$PWD/build/qjs" ~/bin
```

```
qjs --version
QuickJS-ng version 0.6.1
```

```
qjs
QuickJS-ng - Type ".help" for help
qjs > var a = new ArrayBuffer(0, {maxByteLength:16})
undefined
qjs > a.byteLength
0
qjs > a.resize(4)
TypeError: not a function
    at <eval> (<evalScript>:1:1)
```

**Comment by guest271314** [comment]
Got it working building `qjs` from this repository

```
qjs > var a = new ArrayBuffer(0, {maxByteLength:16})
undefined
qjs > a.resize(4)
undefined
qjs > a
ArrayBuffer [ArrayBuffer] {}
qjs > a.byteLength
4
```

**Comment by saghul** [comment]
I haven't updated Txiki.js yet.

**Comment by guest271314** [comment]
For a few months now I have been building QuickJS from the txiki.js dep in the downloaded repository, instead of Bellard's repository, as I had been. I erroneously thought, without checking, txiki.js pulled the latest QuickJS-NG. That's what I get for not following my own rule of vetting everything and everybody, even my own expectations. Thanks for reminding me to scrutinize everything, and expect nothing.

**Comment by saghul** [comment]
Sub modules are pinned to a commit. I usually update when I make a new QuickJS-NG release or there is some significant change I need :-) 

Lately I've been spending more time working on NG, I hope to find some time this week to finish a couple of iterative helper methods and make a new release. A txiki.js release will follow.

**Comment by saghul** [comment]
Oh and txiki hasn't used Bellard's repo pretty much since we started NG.

**Comment by guest271314** [comment]
No worries. 

Resizable `ArrayBuffer` was shipped in Chromium, Firefrox Nightly, Node.js, Deno, and Bun for months before Microsoft TypeScript officially merged the commit that brought that Ecmascript interface into TypeScript world. I was using the `.d.ts` file in the then un-merged PR, and still have to use the merged commit in Deno for `deno check` because `deno` canary from today `2.0.4+770ef14 (canary, release, x86_64-unknown-linux-gnu) v8 12.9.202.13-rusty typescript 5.6.2` is still on TypeScript 5.62, where resizable `ArrayBuffer` was not merged into TypeScript until around 5.7. 

And so on and so forth. 

I noticed txiki.js was using QuickJS-NG a few months ago. I have to pay more careful attention to this. And not just expect developers involved in the same repositories that depend on each other in some way to be using the most updated version in both. 

I know better, really.

**Comment by guest271314** [comment]
@saghul 

> I hope to find some time this week to finish a couple of iterative helper methods and make a new release. A txiki.js release will follow.

FWIW I'm trying to work txiki.js into this runtime agnostic script https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_host.js. I think we still have some work to do over in WHATWG Streams domain.

```
/*
#!/usr/bin/env -S /home/user/bin/deno -A /home/user/bin/nm_host.js
#!/usr/bin/env -S /home/user/bin/node /home/user/bin/nm_host.js
#!/usr/bin/env -S /home/user/bin/bun run /home/user/bin/nm_host.js
*/
import * as process from "node:process";
const runtime = navigator.userAgent;
const buffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
const view = new DataView(buffer);
const encoder = new TextEncoder();
// const { dirname, filename, url } = import.meta;

let readable, writable, exit; // args

if (runtime.startsWith("Deno")) {
  ({ readable } = Deno.stdin);
  ({ writable } = Deno.stdout);
  ({ exit } = Deno);
  // ({ args } = Deno);
}

if (runtime.startsWith("Node")) {
  readable = process.stdin;
  writable = new WritableStream({
    write(value) {
       process.stdout.write(value);
    }
  });
  ({ exit } = process);
  // ({ argv: args } = process);
}

if (runtime.startsWith("Bun")) {
  readable = Bun.file("/dev/stdin").stream();
  writable = new WritableStream({
    async write(value) {
      await Bun.write(Bun.stdout, value);
    },
  }, new CountQueuingStrategy({ highWaterMark: Infinity }));
  ({ exit } = process);
  // ({ argv: args } = Bun);
}

function encodeMessage(message) {
  return encoder.encode(JSON.stringify(message));
}

async function* getMessage() {
  let messageLength = 0;
  let readOffset = 0;
  for await (let message of readable) {
    if (buffer.byteLength === 0 && messageLength === 0) {
      buffer.resize(4);
      for (let i = 0; i < 4; i++) {
        view.setUint8(i, message[i]);
      }
      messageLength = view.getUint32(0, true);
      message = message.subarray(4);
      buffer.resize(0);
    }
    buffer.resize(buffer.byteLength + message.length);
    for (let i = 0; i < message.length; i++, readOffset++) {
      view.setUint8(readOffset, message[i]);
    }
    if (buffer.byteLength === messageLength) {
      yield new Uint8Array(buffer);
      messageLength = 0;
      readOffset = 0;
      buffer.resize(0);
    }
  }
}

async function sendMessage(message) {
  await new Blob([
    new Uint8Array(new Uint32Array([message.length]).buffer),
    message,
  ])
    .stream()
    .pipeTo(writable, { preventClose: true });
}

try {
  // await sendMessage(encodeMessage([{ dirname, filename, url }, ...args]));
  for await (const message of getMessage()) {
    await sendMessage(message);
  }
} catch (e) {
  sendMessage(encodeMessage(e.message));
  exit();
}

export {
  encodeMessage,
  exit,
  getMessage,
  readable,
  sendMessage,
  writable,
};
```

**Comment by bnoordhuis** [comment]
> I hope to find some time this week to finish a couple of iterative helper methods and make a new release

Did you start on the remaining ones yet? Otherwise maybe I'll take a shot tonight or tomorrow.

**Comment by saghul** [comment]
I haven't started yet. Planning on taking a stab tonight if the energy levels allow it 😅

**Comment by bnoordhuis** [comment]
Alright, I'll work on improving line/column numbers then :-)
