### ISSUE TITLE
windows js_module_loader_so support

### ISSUE THREAD

**Issue by zeromake** [quickjs-ng/quickjs#486]
I've done one before by dlfcn-win32, now use win32 api `LoadLibraryW`, `GetProcAddress`, `FreeLibrary` replace unix `dlopen`, `dlsym`, `dlclose`.

Here's my implementation, ignore xmake build file
https://github.com/zeromake/quickjs-ng/commit/86b7df5fc729a8c7535ca14ac2b6229246f5f84e#diff-95fe784bea3e0fbdf30ba834b1a74b538090f4d70f4f8770ef397ef68ec37aa3R482

Run an example
``` pwsh
❯ git clone https://github.com/zeromake/quickjs-ng.git
❯ cd quickjs-ng && xmake f -c -y
❯ xmake b qjsc && xmake b qjs && xmake b fib
❯ xmake r qjs ..\..\..\..\examples\test_fib.js
Hello World
fib(10)= 55
```

But there are still a lot of uncertainties
1. like node native file is `.node` be supported, but quickjs is `.so`.
2. fallback path search? Eg: "./fib.so" find ["./fib.so", "./fib-${platform}-${arch}.so"]
3. cmake test windows local native module support

**Comment by saghul** [comment]
I'd say open a PR and let's go through it!

1. Is of no concern here. On windows shared libraries should have a .dll extension, as is customary.

2. We don't do that for Unix, so not a blocker for Windows.

3. This would be nice yeah, so we are sure it works. There is already a test, it would likely just need some adjustments.

**Comment by zeromake** [comment]
@saghul ok, I'll bring the PR out first later
