### ISSUE TITLE
todo: back-port some fixes

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#492]
Minor correctness fixes but pretty intrusive and don't cherry-pick cleanly:

- bellard/quickjs@10fc744ae4dfe59b685f5643b71530891cf0be3b (probably the easiest one)
- bellard/quickjs@af308614a8b89e80a6e6a3f270292ef724931d1e
- bellard/quickjs@f25e5d4094a11cf098670417e8a16ffb7cbadda0

There's also bellard/quickjs@efdb722f029a62776dc64abe2d122f5b4fd29ab5 for a test that does `eval("import('./module-code_FIXTURE.js');")` that I fixed... quite differently... in 64c9ac539264f1db7d260e236db2a1dca2c727bf :-)

**Comment by saghul** [comment]
First: https://github.com/quickjs-ng/quickjs/pull/534
Middle one: https://github.com/quickjs-ng/quickjs/pull/531
Last one: https://github.com/quickjs-ng/quickjs/pull/533

**Comment by saghul** [comment]
All done!
