### ISSUE TITLE
This simple example of JS_GetModuleNamespace can't be run successfully.

### ISSUE THREAD

**Issue by JustDooooIt** [quickjs-ng/quickjs#493]
the minimal reproducible project
[qjs-issue.zip](https://github.com/user-attachments/files/16840620/qjs-issue.zip)

**Comment by saghul** [comment]
In your example your are compiling the module (JS_EVAL_FLAG_COMPILE_ONLY) but not evaluating it. I think you need to add `JSValue mod = JS_EvalFunction(ctx, ret);` and then try and extract the namespace from there.

**Comment by JustDooooIt** [comment]
> In your example your are compiling the module (JS_EVAL_FLAG_COMPILE_ONLY) but not evaluating it. I think you need to add `JSValue mod = JS_EvalFunction(ctx, ret);` and then try and extract the namespace from there.
It worked,thx.
