### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#5]
The current documentation is pretty limited and one of the things I'd very much like to work on is making that better.

In the past I've worked documenting 2 large-ish projects, with different frameworks:

- libuv: used Sphinx, which is a documentation framework and does have some ergonomics for C. Uses RST for the document format (there is a MD plugin now, but I'm not familiar with it). Live: http://docs.libuv.org/en/v1.x/
- Jitsi Meet: used Docusaurus, which is more generic and can actually be a whole site with news articles, etc. Uses MD for the document format. Live: https://jitsi.github.io/handbook/

After working with both I now lean towards Docusaurus. It's easy to setup and maintain, much to my surprise, I'll admit! Since it's kinda free-form we can document the API the way we like and perhaps use the blog / news section to announce releases?

Thoughts?

**Comment by saghul** [comment]
@bnoordhuis I'd like to get started here, any strong opinions either way?

**Comment by bnoordhuis** [comment]
As long as there's no passive voice in our docs I'm fine either way. :-)

Docusaurus then?

**Comment by saghul** [comment]
Right on, I'll get started soon!

**Comment by ammarahm-ed** [comment]
I am not an expert at QuickJS internals but I can help write the docs.

**Comment by saghul** [comment]
Thanks! I hope to put together the start of it this coming week.

**Comment by saghul** [comment]
Fixed in https://github.com/quickjs-ng/quickjs/commit/7cfedb095235c82d819bcba0ac7a29944fc1f044

Now on to adding more docs!
