### ISSUE TITLE
RFC: check-in generated code files or not?

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#509]
Original by @chqrlie:

> Yes, this is unfortunate. We should try and find a way to generate these files at build time and avoid committing them. This would also reduce bloat in the repository.

**Comment by saghul** [comment]
> I am not sure I understand the connection with the xz fiasco. We shall be very cautious about accepting PRs from, let alone giving commit rights to outsiders.

> Generating the byte code files at build time is mainly a problem for cross compiling where it requires building a qjs executable for the host in addition to cross compiling for the selected target. This used to be problematic because the generated files depended on the endianness of the target, which is no longer the case.

The connection with xz is that if the concept of "release tarball" is introduced, there is opportunity to add files which aren't in git. Right now things are visible in plain sight.

As for cross-compiling, yeah that becomes annoying. Building for WASM for example, you'd first need to build for the host just to generate the bytecode files, then rebuild everything. Doable but annoying.

Honestly, coming up with the necessary CMake voodoo to do that is more annoying than having the C files checked in :-P

My 2 cents!

**Comment by bnoordhuis** [comment]
I'm perfectly fine with the status quo. The huge diffs are mildly annoying but I like having everything versioned.

**Comment by saghul** [comment]
Same here!
