### ISSUE TITLE
valgrind eats away our GH actions credit

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#518]
The free tier gives us 2000 monthly minutes.

We run valdrind on every push to master, and that takes 40 minutes to run.

When we get into it valgrind just runs too many times eating away precious time.

Proposal:

- Run it once a week on a cron job
- Still be able to manually run it
- Run a LSan job in addition to the existing ones to compensate for the valgrind one running less often

Other ideas?

@bnoordhuis

**Comment by saghul** [comment]
For reference, the latest job that fully ran took `1h 36m 23s` of GHA time.

**Comment by bnoordhuis** [comment]
Is that why the CI jobs are so backed up right now? We'll have to run the valgrind job as a cron job then.

GitHub used to be pretty laid back about raising limits for bona fide open source projects if you asked, but that was pre-acquisition; things may have changed.

**Comment by bnoordhuis** [comment]
Now that I think about it: we could be more restrictive about _when_ valgrind runs. Right now, _every_ push to master results in a valgrind run, but it's probably only necessary when *.[ch] files change (and not even all of them.)

**Comment by saghul** [comment]
> Is that why the CI jobs are so backed up right now? We'll have to run the valgrind job as a cron job then.
> 
> GitHub used to be pretty laid back about raising limits for bona fide open source projects if you asked, but that was pre-acquisition; things may have changed.

I'm not 100% sure that's the reason or there was some kind of outage. The status page said nothing, and cancelling and retrying worked... sometimes!

Let's monitor and see if it repeats.

**Comment by past-due** [comment]
Credit shouldn’t apply to public repositories?

From https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions :

> **_GitHub Actions usage is free for standard GitHub-hosted runners in public repositories_**, and for self-hosted runners. _For private repositories_, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the account's plan.

(Emphasis mine.)

**Comment by saghul** [comment]
Maybe GHA was just having a bad day 😅

I'll close and reopen if necessary.
