### ISSUE TITLE
MSVC build error?

### ISSUE THREAD

**Issue by wuqi** [quickjs-ng/quickjs#522]
![image](https://github.com/user-attachments/assets/e43e4309-32f2-4094-a0a3-09093893f4c0)

The   `__extension__`  in quickjs.c makes a lot of compile errors when use msvc2022,clang is ok.I don't know how to correct it
![image](https://github.com/user-attachments/assets/b5c6602e-7f98-440f-8672-98688fc6ad01)

**Comment by saghul** [comment]
I was looking into something similar yesterday. 

I think you can drop the extension marker and ignore warning C4200 and it should work.

**Comment by wuqi** [comment]
> I was looking into something similar yesterday.
> 
> I think you can drop the extension marker and ignore warning C4200 and it should work.

Thank you ,I define the `__extension__`  to empty and it works.
