### ISSUE TITLE
Unicode needs to be updated to 16.0.0

### ISSUE THREAD

**Issue by linusg** [quickjs-ng/quickjs#530]
https://www.unicode.org/versions/Unicode16.0.0/

**Comment by saghul** [comment]
FTR, the latest update was to 15.0, as heavier changes were necessary for 15.1: https://github.com/quickjs-ng/quickjs/issues/77

**Comment by bnoordhuis** [comment]
Done just now in 243b968ee12068b721ca2613ff3d0e01ab5dc2ea, in ominously numbered pull request #666.
