### ISSUE TITLE
Support private brand checks

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#541]
I thought we already did but we don't. This should work but currently fails to parse `#p in o`:
```js
class C { #p; static m(o) { return #p in o } } // SyntaxError: unexpected token in expression: '#p'
```
https://v8.dev/features/private-brand-checks

**Comment by saghul** [comment]
I have a vague memory of Fabrice fixing something related, and indeed, it does run there, so I assume we just need a port...

**Comment by saghul** [comment]
Maybe https://github.com/bellard/quickjs/commit/3ab1c2b3148d1c70181607002aac23ecdd2ad482 ?
