### ISSUE TITLE
'undefined' returned instead of undefined in string split with regex

### ISSUE THREAD

**Issue by malbarbo** [quickjs-ng/quickjs#565]
node and deno evaluates the expression `"a ".split(/(d)*/)`  to `[ "a", undefined, " " ]`, but quickjs-ng evaluates to `[ 'a', 'undefined', ' ' ]`.

**Comment by bnoordhuis** [comment]
Kind of surprising because e.g. `exec()` does work correctly - and apparently test262 doesn't test it? Doubly surprising.

Anyway, legit bug - I'll fix it.
