### ISSUE TITLE
Parse error (not existing with vanilla QuickJs)

### ISSUE THREAD

**Issue by arabine** [quickjs-ng/quickjs#572]
I'm trying to execute PouchDB 9.0.0 with some stubs. 

I have a parsing error that I don't have with QuickJS "vanilla":

```
SyntaxError: expecting ';'
    at ../pouchdb-9.0.0.js:10537:75
```

Here is the line (maybe you will need more lines to understand, you can look at the library file:

```
await upsert(sourceDB, '_local/' + localDocName, diffFunction);
```

Reproduction depot : https://github.com/arabine/quickjs-browser-env

```
mkdir build
cd build
cmake ..
make
```

**Comment by saghul** [comment]
Do you have a small(er) repro case?

**Comment by bnoordhuis** [comment]
I think I kind of see the bug: the parser appears to consume one or two tokens too much.

I'm not 100% sure what throws it off track but it happens at the bottom of `js_parse_statement_or_decl()`, in the last call to `js_parse_expect_semi()`.

**Comment by arabine** [comment]
> Do you have a small(er) repro case?

Sure:
```
git clone https://github.com/quickjs-ng/quickjs
cd quickjs/
mkdir build && cd build
cmake ..
make
wget https://github.com/pouchdb/pouchdb/releases/download/9.0.0/pouchdb-9.0.0.js
./qjs pouchdb-9.0.0.js
SyntaxError: expecting ';'
    at pouchdb-9.0.0.js:10537:75
```

**Comment by saghul** [comment]
I think the problem is that the module detection doesn't work, so it parses it as a script.

This "works":

```
./build/qjs -I globals.js t.js
```

Where globals is:

```
globalThis.self = globalThis;
globalThis.fetch = () => {};
globalThis.Headers = function() {};
```

And t.js

```
import * as pdb from './pouchdb-9.0.0.js';

console.log("hello");
```

If you just try to run the script it will try to parse it as a script, since it doesn't detect it as a module. Importing it will make it so its parsed as a module.

**Comment by saghul** [comment]
I think we are missing https://github.com/bellard/quickjs/commit/c06c399f4f8f8292e65e848ff3468f302c18a55e

**Comment by arabine** [comment]
Nice, ok I see. But the behavior is different wtih QuickJS on that point (no error shown with the same "bad" usage).

**Comment by saghul** [comment]
This PR fixes it: https://github.com/quickjs-ng/quickjs/pull/573

With it I get the ReferenceError not the SyntaxError.
