### ISSUE TITLE
Qjs still compiles only for vs2022

### ISSUE THREAD

**Issue by satk0** [quickjs-ng/quickjs#586]
Hello again, I've recently made a PR when using qjs with radare2. And unfortunately `__STDC_NO_ATOMICS__` is not working for detection whether `/experimental:c11atomics` flag is set.

You can see checks failing for r2 build [here](https://github.com/radareorg/radare2/pull/23438). 

What's worse, it seems like [there is no macro to detect that](https://developercommunity.visualstudio.com/t/add-stdatomich-support-for-c11/1204057#T-N10607273)

Because of that, using `c11atomics` in msvc is extremely experimental and works only for vs2022. No other vs versions has this feature. Could qjs therefore also omit atomics to make msvc build with other vs versions?

**Comment by satk0** [comment]
Maybe there could be some custom preprocessor macro defined to support both worlds?

**Comment by saghul** [comment]
> Maybe there could be some custom preprocessor macro defined to support both worlds?

Perhaps it can be detected at compile time and then a define can be set which we'd use in the code.

**Comment by satk0** [comment]
I wish it could, I've posted [a question on vs forum.](https://learn.microsoft.com/en-us/answers/questions/2100492/how-can-i-check-for-experimental-c11atomics-flag-i) Got no response...

**Comment by saghul** [comment]
I think this can work? https://cmake.org/cmake/help/latest/module/CheckCSourceCompiles.html

**Comment by satk0** [comment]
Wait, that might help radare2:

> The MSVC implementation defines it as 1 when compiled as C and one of the [/std](https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170) C11 or C17 options is specified

Source: https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170

Basically, setting `/std:c11` or `/std:c17` on compilation should do the job

**Comment by saghul** [comment]
Oh! Maybe setting "set(CMAKE_C_STANDARD 11)" as we do is not enough?

**Comment by satk0** [comment]
I don't know, Honestly I think a good idea would be to create a ci/cd check for compiling msvc without `/experimental:c11atomics` and see how it goes. I'd be glad to take care of that by making a PR :smiley:

**Comment by satk0** [comment]
Ok, after adding `-Dc_std=c11` to meson it works on r2, so I am sure it will work also for cmake :smiley:

**Comment by saghul** [comment]
We are already setting it. I guess a good thing would be to add a CI with msvc < 2022. Are you up for that?

**Comment by satk0** [comment]
Sure
