### ISSUE TITLE
Iterate list of exports from C

### ISSUE THREAD

**Issue by KaruroChori** [quickjs-ng/quickjs#594]
Hi, I noticed that quickjs has functions like `JS_AddModuleExport` to manipulate the export list of a module, but I cannot figure out how to iterate its elements from the outside. Have I missed something?

**Comment by saghul** [comment]
Hey @KaruroChori ! You can use JS_GetOwnPropertyNames to enumerate the properties of the object.

**Comment by KaruroChori** [comment]
I tried before, but I think I am missing two pieces of information to make it work.
Let's say I have the following script:
```js
export const fnA = ()=>{console.log("Hello World");}
const fnB = ()=>{console.log("Hallo Welt");}
```
Those two are not recorded on the global object, so I cannot enumerate them from `JS_GetGlobalObject(ctx)`. Is there a symbol `module` or something like that?
~~Regardless, just using `GetOwnPropertyNames` on `globalThis` for test, I am returned a list of atoms, and when I try to convert them to cstring via `JS_AtomToCString` they are all resulting in `Object` which is not very useful :D. I guess I am treating them wrong, but I really cannot see how.~~ no it was just a skill issue of mine.

For reference:
```
    const char* program ="...";
    
    auto result = JS_Eval(ctx, program, strlen(program), "<input>", JS_EVAL_TYPE_MODULE);
    JS_FreeValue(ctx,result);

    JSPropertyEnum* list = nullptr;
    uint32_t list_items;
    auto globalThis = JS_GetGlobalObject(ctx);

    JS_GetOwnPropertyNames(ctx,&list,&list_items, globalThis,JS_GPN_STRING_MASK|JS_GPN_SYMBOL_MASK|JS_GPN_PRIVATE_MASK);
        std::cout<<list_items<<"\n\n";

    for(int i=0;i<list_items;i++){
        auto tmp = JS_AtomToCString(ctx, list->atom);
        vs_log(severety_t::OK,nullptr,"Symbol found. Adding it. %s", tmp);
        JS_FreeCString(ctx, tmp);
    }
    JS_FreeValue(ctx, globalThis);
    JS_FreePropertyEnum(ctx, list, list_items);
```

**Comment by KaruroChori** [comment]
Please ignore the all `Object` part. I should sleep at night instead of forgetting I have one more index on double pointers.
