### ISSUE TITLE
Will a Tracing GC be implemented in quickjs-ng?

### ISSUE THREAD

**Issue by buddyliao** [quickjs-ng/quickjs#598]
Since the GC of quickjs is ref count, it is not resource friendly, will a tracing gc be implemented in quickjs-ng? Thanks.

**Comment by saghul** [comment]
It's not on our TODO list at the moment.

What problem would that solve for you?

**Comment by bnoordhuis** [comment]
> is not resource friendly

Strong claim, probably wrong, but too unspecific to address. You should elaborate.

The garbage collector uses reference counting with cycle breaking to avoid space leaks in code like:
```js
var a = {}, b = {}; a.b = b; b.a = a;
```
Tracing GC is not necessarily superior and possibly inferior for many workloads. Memory footprint is an important reason to pick quickjs over other JS engines and mean memory footprint, _ceteris paribus_, is higher with tracing GC.

**Comment by bnoordhuis** [comment]
No follow-up from OP, closing.
