### ISSUE TITLE
JS_DetectModule does not (always) detect TLA

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#606]
Works:
```
await Promise.resolve(42)
```
Does not work:
```
const p = Promise.resolve(42)
await p // SyntaxError: expecting ';'
```
Looks like 6dd2ce308a282bc26c192dfa314f484cbab655db was only a partial fix?

**Comment by saghul** [comment]
Yes, the detection is quite naive and only checks the 1st line after skipping comments iirc.
