### ISSUE TITLE
quickjs is not compatible with ucrt of Windows SDK 26100 

### ISSUE THREAD

**Issue by twinstar6980** [quickjs-ng/quickjs#622]
The macro definition `NAN` is used in quickjs.c.
https://github.com/quickjs-ng/quickjs/blob/0c8aeb1d5093869479e914980ef5588020bce64a/quickjs.c#L40297

For Windows platform, NAN is defined in `ucrt/corecrt_math.h`.
In Windows SDK 22621:
```c
#define NAN ((float)(INFINITY * 0.0F))
```
In this case, the compiler can complete the compilation, but Microsoft has made changes in Windows SDK 26100:
```c
#define _UCRT_NAN (__ucrt_int_to_float(0x7FC00000))
#define NAN _UCRT_NAN
```
When using SDK 26100, the compiler (msvc-cl 19.41 or clang-cl 19.1) will report an error: C2099 initializer is not a constant.

Is there any way to solve this problem?

**Comment by twinstar6980** [comment]
When using SDK 26100, we can add the macro `_UCRT_NOISY_NAN` to make the definition of `NAN` consistent with 22621, but I don't know whether this macro will have other effects?

**Comment by 695137400** [comment]
我最初也是用终端控制台编译，会报错，后来改用了clion，直接导入cmake项目就行，不报错，完美

**Comment by twinstar6980** [comment]
> 我最初也是用终端控制台编译，会报错，后来改用了clion，直接导入cmake项目就行，不报错，完美

你的clion用的是minggw还是msvc全家桶？能麻烦下在clion里看看NAN是怎么定义的么？

**Comment by twinstar6980** [comment]
I tested the value of NAN under different conditions:
`/fp:precise`（default）
(-)22621: fff8000000000000
(+)22621(_UCRT_NEGATIVE_NAN): 7ff8000000000000
(-)26100(_UCRT_NOISY_NAN): fff8000000000000
(+)26100(_UCRT_NOISY_NAN,_UCRT_NEGATIVE_NAN): 7ff8000000000000
(+)26100: 7ff8000000000000
(-)26100(_UCRT_NEGATIVE_NAN): fff8000000000000

Even if defined `_UCRT_NOISY_NAN`, NAN is also quiet (why not noisy/signaling?). If `/fp:strict` is enabled, 22621 and 26100(_UCRT_NOISY_NAN) will produce positive NAN values.

I don't know if the behavior of quickjs depends on the specific value of NAN. If not, should we add `_UCRT_NOISY_NAN` macro definition in cmake to be compatible with sdk26100?

**Comment by saghul** [comment]
Interesting! Do you know how to use that version in a GH Action so we can add a CI?

**Comment by twinstar6980** [comment]
> Interesting! Do you know how to use that version in a GH Action so we can add a CI?

maybe you can use this repo: https://github.com/GuillaumeFalourd/setup-windows10-sdk-action

**Comment by saghul** [comment]
Looks like 26100 doesn't work though: ` (26100 returns an error)`

**Comment by 695137400** [comment]
![2024-10-25_155809](https://github.com/user-attachments/assets/35f33dee-bff6-4e8a-9158-f3f1c3ab6979)

**Comment by 695137400** [comment]
![Uploading 2024-10-25_160422.png…]()

**Comment by 695137400** [comment]
![2024-10-25_160422](https://github.com/user-attachments/assets/2033bdaf-67b4-473c-941f-86efe357f141)

**Comment by saghul** [comment]
Not sure what you're asking here.

**Comment by twinstar6980** [comment]
> Looks like 26100 doesn't work though: ` (26100 returns an error)`

Try this: https://github.com/marketplace/actions/windows-sdk-install
I did a simple test and it was able to install sdk26100 successfully.

**Comment by twinstar6980** [comment]
> ![2024-10-25_160422](https://private-user-images.githubusercontent.com/13709135/380067379-2033bdaf-67b4-473c-941f-86efe357f141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTE5OTMsIm5iZiI6MTcyOTg1MTY5MywicGF0aCI6Ii8xMzcwOTEzNS8zODAwNjczNzktMjAzM2JkYWYtNjdiNC00NzNjLTk0MWYtODZlZmUzNTdmMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDA5MTI1ZWMyYjhiMWIzMDI1ZDZkMWFhZDNjYWY5NmM2NzlkMGRhODA3ODFkNDRlNTJkNTgxNTc2YzE5YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mZMTRiTH1FWAv2qchjUeeBU1jE-HKiK7nJNnCf3NhCg)

emm，我不太了解 mingw ，这个错误是因为最新版本 winsdk ucrt 更改后的 NAN 宏不再能作为编译期常量来使用。你用 mingw 工具链没触发这个问题应该是因为 mingw 内部自己实现了 NAN 的定义，而没有走 ucrt 的 NAN 定义。这与这个 issue 无关。

**Comment by bnoordhuis** [comment]
> I don't know if the behavior of quickjs depends on the specific value of NAN

Yes. From libbf.c (handles BigInts):

https://github.com/quickjs-ng/quickjs/blob/89883ae6570f62d3961607f3b64b5673dc1acdc8/libbf.c#L2463-L2464

Changing JS_NAN also changes the output of JS_WriteObject, the serializer. That's not exactly fatal but it would be annoying to have two machines produce different output for the same input.

**Comment by twinstar6980** [comment]
The WinSDK version can be set in CI via:
```yaml
  - name: Install windows sdk
    uses: ChristopheLav/windows-sdk-install@v1
    with:
    version-sdk: 26100
    features: 'OptionId.DesktopCPPx86,OptionId.DesktopCPPx64'
```
And specify `-DCMAKE_SYSTEM_VERSION:STRING=10.0.26100.0` in the cmake command line.

.
Regarding specific values ​​for nan:
In winsdk 22621 and earlier, the NAN macro produces negative nan (unless `/fp:strict` is specified), which does not seem to be the value expected by libbf. However, quickjs-ng has always worked this way on windows before winsdk 26100.
Specifying `_UCRT_NOISY_NAN` will revert the behavior of nan to that before 22621. If you don't want to use it, it seems that you must refactor the relevant code to not rely on the "compile-time constant" feature.

**Comment by saghul** [comment]
I'll try to get back to this next week!
