### ISSUE TITLE
SyntaxError thrown on valid JS

### ISSUE THREAD

**Issue by p-bakker** [quickjs-ng/quickjs#633]
This snippet of code throws a SyntaxError: invalid lexical variable name:
```
        with (new Proxy({globalThis: {Infinity, NaN, undefined}}, {})) {
          const {Infinity,NaN,undefined} = this.globalThis;
        }
```
This sort of structure is used by SES in the Compartment polyfill

Besides this snippet being valid js and thus shouldn't be throwing a SyntaxError, if there would be a real syntax error, shouldn't the error include the invalid variable name?

**Comment by chqrlie** [comment]
This snippet can be simplified as

    { const { undefined } = {} }

it throws:

    SyntaxError: invalid lexical variable name
        at <evalScript>:1:8

Same problem without the destructuring:

    { const undefined = void 0; }

**Comment by chqrlie** [comment]
> Besides this snippet being valid js and thus shouldn't be throwing a `SyntaxError`, if there would be a real syntax error, shouldn't the error include the invalid variable name

I agree on both counts.  Adding the identifier should be easy in this case because this is a parse error.
