### ISSUE TITLE
qjs fails to output content via stdout to pipe or non-console receiver

### ISSUE THREAD

**Issue by harig** [quickjs-ng/quickjs#635]
After 72d4587163066 content emitted by qjs (via console.log/print etc. ) to stdout fails to reach a receiver through a pipe or other process reading from its stdout on Windows 10. 
For example, if we run the following inside cmd.exe
`qjs -e "print(1);"`  
will print 1
`qjs -e "print(1);" | cat `
will not output anything.
Similar issue can be seen with qjs launched as a process and some other program reads its output.

**Comment by bnoordhuis** [comment]
Yeah, I'm not too surprised that broke. Pull request welcome.

You can use something like this to detect whether stdout refers to the console:
 ```c
#ifdef _WIN32
int isatty(int fd) { // if (isatty(1)) { /* ... */ } else { /* ... */ }
    DWORD mode;
    HANDLE handle = (HANDLE)_get_osfhandle(fd);
    if (GetFileType(handle) == FILE_TYPE_CHAR)
        if (GetConsoleMode(handle, &mode))
            return 1;
    return 0;
}
#endif
```
There's one very annoying gotcha though: `_get_osfhandle()` asserts in msvcrt debug builds if the file descriptor is invalid. You _can_ suppress it with `_CrtSetReportHook` but it's super kludgy and libraries shouldn't touch that.

Hooking it in qjs.c is fine but not in quickjs-libc.c.

**Comment by bnoordhuis** [comment]
@harig can you test #642 and report back?
