### ISSUE TITLE
qjs-ng doesnt work when compiled with asan

### ISSUE THREAD

**Issue by satk0** [quickjs-ng/quickjs#636]
Hey Again, pancake has just found out, that compiling qjs-ng with asan enabled, makes qjs-ng unusable:
![image](https://github.com/user-attachments/assets/c4c2657f-bd50-466c-b182-6e4f13ac374d)

It was already solved by pancake in r2, here: https://github.com/radareorg/radare2/commit/fd4bbe063b95bbdd06fcf31be19e8fde566cfa28

It would be great to patch it upstream. Can I get a green light for making a PR implementing just that?

**Comment by bnoordhuis** [comment]
We build and test with asan (and ubsan and....) on the CI so it should already work out of the box.

Do you build with NDEBUG defined or without? I ask because of this:

https://github.com/quickjs-ng/quickjs/blob/eae9b23843ef6c29a2acb7caab53a9b46f772d34/quickjs.c#L2481-L2489

**Comment by saghul** [comment]
Sounds related to https://github.com/quickjs-ng/quickjs/pull/521

**Comment by satk0** [comment]
Thanks for the quick response, we undefine NDEBUG here: https://github.com/radareorg/radare2/blob/189610e66471342e01ca2df60188930f47af1749/shlr/qjs/Makefile#L29

**Comment by saghul** [comment]
Ah, I see you are not using our build system. We define `__ASAN__` when compiling under it. Can you try doing that?

**Comment by satk0** [comment]
Sure, I am trying it rn, I am sure it's going to work

**Comment by satk0** [comment]
Thanks, I've made a PR defining the variable you requested here: https://github.com/radareorg/radare2/pull/23556

Will see what pancake will say. Will inform you on that

**Comment by trufae** [comment]
Any reason not to use the preprocessor directive instead of the custom __ASAN__ ?
![Screenshot_2024-10-28_at_10 08 13](https://github.com/user-attachments/assets/c0b8510c-6bbc-4b02-9075-c492813efaef)

**Comment by saghul** [comment]
Assuming this still holds true: https://stackoverflow.com/a/78444624

GCC (at least not in all versions with support for ASAN) doesn't have `__has_feature` so we'd have to check for `__SANITIZE_ADDRESS__`, which in turn Clang doesn't support.

So using our own seems more fool proof here.

**Comment by trufae** [comment]
Sounds good, i guess visual studio situation is even worse, but this ifdef at least saved me some time. But considering there’s no generic way to check this sounds like the way to go. Thanks

**Comment by satk0** [comment]
Thanks for all, I can close the issue now, sorry for taking your time

**Comment by saghul** [comment]
No problem @satk0 !

**Comment by bnoordhuis** [comment]
I landed a fix just now ([56e5ffa](https://github.com/quickjs-ng/quickjs/commit/56e5ffa2dba3185253647ade5e1f9275e1221acf)) so there should be no changes necessary anymore on r2's side.
