### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by TooTallNate** [quickjs-ng/quickjs#664]
Highly anticipating the 0.6.2 (or 0.7.0?) release. Any idea on timeline?

Kudos to @bnoordhuis, @saghul, and all other contributors 😄

**Comment by saghul** [comment]
I think finishing iterative helpers would be good since they now throw. A week or 2 I think?

**Comment by bnoordhuis** [comment]
@saghul did you start on the remaining Iterator methods yet? Else I'll have a go.

**Comment by saghul** [comment]
Yep, I got the scaffold and `drop` almost done. Hope to send the 1st PR tonight / tomorrow.

**Comment by saghul** [comment]
@bnoordhuis Everything I had in mind for this release (including the update to the docs) has landed already (thanks for the reviews!). Shall I make a release tonight?

**Comment by bnoordhuis** [comment]
Yep, let's do it.

**Comment by saghul** [comment]
🔥

**Comment by saghul** [comment]
0.7.0 is out! https://github.com/quickjs-ng/quickjs/releases/tag/v0.7.0
