### ISSUE TITLE
[discuss] versioning

### ISSUE THREAD

**Issue by saghul** [quickjs-ng/quickjs#675]
As we move forward and make releases, we have 3 types of compatibility to consider:

- API
- ABI
- Bytecode (BC)

The first 2 can be ignored while we work in the safety of 0.X releases ;-) but if / when we decide to go 1.0 (assuming we decide to stick with SemVer) the BC version might be problematic.

There is a high chance a new minor version needs to bump the BC version, for example because we implement a new ES feature that requires that.

How do we want to handle that? Everything is on the table:

- Use a different versioning scheme, perhaps where the major number is the (or tied to) BC version?
- Stick to SemVer, but make the BC updates prominent in the changelog

Both WFM, but I'm worried the 1st option would end up bumping the major too much?

Feels like we might want to expose BC_VERSION in some JS_GetBytecodeVersion for those who want to maintain compatibility across versions, if that makes any sense...

Thoughts?

**Comment by bnoordhuis** [comment]
Third option: retain compatibility with older formats. The serializer only writes the new format but the deserializer understands old and new formats.

Pros: format changes are semver-minor (right?)
Cons: lot of work, probably a bug magnet
<hr>

Fourth option: only extend the wire format, never change it. Add new BC tags as needed but don't remove or change existing ones.

Pros: maybe less work than (3)
Cons: less work != no work, still plenty of room for bugs
<hr>

Both lead to much additional maintenance complexity, and that complexity only increases over time, it never decreases.

It's still early days, I'll worry about that some other year :-)

**Comment by saghul** [comment]
> It's still early days, I'll worry about that some other year :-)

😅  fair enough!

**Comment by kapouer** [comment]
Please see also https://github.com/ada-url/ada/issues/827#issuecomment-3289520898 for an easy-to-use tool to track versioning (abidiff from abigail-tools).
