### ISSUE TITLE
ES Compat Issue with Iterator prototypes

### ISSUE THREAD

**Issue by p-bakker** [quickjs-ng/quickjs#707]
This is supposed to yield true, but in QJS-NG it yields false:
Object.getPrototypeOf(Object.getPrototypeOf(Array.prototype[Symbol.iterator]())) === Iterator.prototype

This causes SES lockdown to not work

**Comment by saghul** [comment]
I'll take a look!

What is SES lockdown?

**Comment by p-bakker** [comment]
The lockdown method of (the) Secure EcmaScript (shim): https://github.com/endojs/endo/blob/master/packages/ses/README.md#lockdown

**Comment by saghul** [comment]
Not sure it's the MD syntax in your first post, but the correct code would be 

`Object.getPrototypeOf(Object.getPrototypeOf(Array.prototype[Symbol.iterator]())) === Iterator.prototype`

which does work.

`Array.prototype[Symbol.iterator]` will return a function you need to call to get the iterator.

**Comment by p-bakker** [comment]
That was indeed a markdown thing

For me `Object.getPrototypeOf(Object.getPrototypeOf(Array.prototype[Symbol.iterator]())) === Iterator.prototype` in quickjs-ng evaluates to false. Not for you?

**Comment by saghul** [comment]
That does work for me indeed. What commit are you on?

**Comment by p-bakker** [comment]
My bad, must've messed up something pulling in the latest quickjs-ng when building quickjs-emscripten. Have redone it and now this problem has disappeared
