### ISSUE TITLE
Run test suite under valgrind

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#71]
Valgrind catches bugs that {A,M,UB}San won't catch. The downside is it's sloooow and maybe not something we want to run for every commit.

Test how long it takes on GHA. If it's beyond reasonable, then run it daily as a [GHA cron job](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)?

**Comment by saghul** [comment]
Would you run the entire 262 suite or a subset?

**Comment by bnoordhuis** [comment]
The whole suite.

**Comment by saghul** [comment]
I'm trying this locally and it's unbearably slow, let's see how it does in the CI: https://github.com/quickjs-ng/quickjs/pull/324 at least it seems to have caught something... https://github.com/quickjs-ng/quickjs/issues/323
