### ISSUE TITLE
Support console.groupEnd

### ISSUE THREAD

**Issue by p-bakker** [quickjs-ng/quickjs#710]
Current console impl. supports .group and .groupCollapsed, but not the accompanying .groupEnd method

Which bombs out libraries the start groups with .group or .groupCollapsed end then try to close the group with .groupEnd

**Comment by saghul** [comment]
Our console implementation is pretty barebones and only supports log: https://github.com/quickjs-ng/quickjs/blob/ef1541880778c16a17f678ddb4321268e30b9902/quickjs-libc.c#L3985

Having a full blown implementation of console is not something we are considering I'd say.

/cc @bnoordhuis

**Comment by bnoordhuis** [comment]
I'm not vehemently opposed to adding .group/.groupCollapsed/.groupEnd. But.

- .groupCollapsed is meaningless for CLI apps like qjs. I guess it should act like .group? I think that's what node does

- is .group indentation a process-global or a per-context property? If the latter, it could be stored on `JSThreadState`

**Comment by saghul** [comment]
I think the emscripten wrapper provides a partial console implementation, that's probably what causes the confusion.

**Comment by p-bakker** [comment]
>  think the emscripten wrapper provides a partial console implementation, that's probably what causes the confusion.

Ah, sry for jumping to the wrong conclusion...
