### ISSUE TITLE
Bad js_os_exec performance with high file descriptor limit

### ISSUE THREAD

**Issue by bnoordhuis** [quickjs-ng/quickjs#711]
js_os_exec tries to close all fds in the range 3..sysconf(_SC_OPEN_MAX). When `ulimit -n` is set to something high (1 million on my system), that takes considerable time.

Maybe the loop is the best we can do on other systems, but on linux, replacing it with `close_range(3, INT_MAX, 0)` should speed it up considerably.

**Comment by saghul** [comment]
bellard/QuickJS landed such patch. I didn't think it was worth it but if you feel inclined let's have it.
