### ISSUE TITLE
Compiling with CMake & Clang on Windows with MSVC ABI (not using clang-cl or the MSVC toolchain) causes QuickJS to try to link to `m.lib`

### ISSUE THREAD

**Issue by Oliver-makes-code** [quickjs-ng/quickjs#728]
Title is descriptive enough.

**Comment by saghul** [comment]
What CMake incantation do you use to compile that way?

I guess it's not surprising since we do link to libm on Unix for the math functions.

**Comment by Oliver-makes-code** [comment]
The problem is here: https://github.com/quickjs-ng/quickjs/blob/master/CMakeLists.txt#L215-L217

It's checking for MSVC, which is only set when CMake uses `cl` or `clang-cl` (we're using normal `clang`)
But since Clang is using MSVC's ABI (Target `x86_64-pc-windows-msvc`) it needs to link to MSVC's libraries

**Comment by saghul** [comment]
You don't answer my question though. How do you target that?

**Comment by Oliver-makes-code** [comment]
The `llvm` package on Chocolatey, by default, uses MSVC ABI. Otherwise you can use `-target x86_64-pc-windows-msvc` in the command line arguments. See https://clang.llvm.org/docs/CrossCompilation.html

**Comment by saghul** [comment]
Thanks for explaining, let's continue in the PR.
