### ISSUE TITLE
command `qjsc` not installed by cmake(make install)

### ISSUE THREAD

**Issue by terrywh** [quickjs-ng/quickjs#730]
command `qjsc`which is built but not installed by cmake (make install):
<img width="484" alt="Clipboard_Screenshot_1733124195" src="https://github.com/user-attachments/assets/f51192be-c9df-4762-95e7-40e7cd565498">

**Comment by saghul** [comment]
Good catch! Fix: https://github.com/quickjs-ng/quickjs/pull/731
