### ISSUE TITLE
Breaks and labels interact incorrectly

### ISSUE THREAD

**Issue by WardBrian** [quickjs-ng/quickjs#741]
This is essentially me duplicating https://github.com/bellard/quickjs/issues/275 here, since it seems to still affect quickjs-ng:

```shell
./qjs-linux-x86_64 -e 'for (var i=0; i<4; i++)
label: {
  console.log(i);
  if (i === 1) {
    console.log("break");
    break;
  }
}'
```
prints
```
0
1
break
2
3
```

When the expected output does not print `2` or `3`.

In particular, this seems to be an issue when using quickjs with code created the [js_of_ocaml](https://github.com/ocsigen/js_of_ocaml) Ocaml->JS compiler, as this has moved to heavy use of labels and break statements for https://github.com/ocsigen/js_of_ocaml/pull/1496

**Comment by bnoordhuis** [comment]
Hah, it's even worse - the `while` variant just hangs:
```js
var i = 0; while (i < 3) label: {
  if (i > 0) break
  i++
}
```
Fix incoming!

**Comment by bnoordhuis** [comment]
For posterity: the fix also fixes https://github.com/bellard/quickjs/issues/282

**Comment by saghul** [comment]
Ha, nice one!
