### ISSUE TITLE
No way to get `this` from super call in C

### ISSUE THREAD

**Issue by Oliver-makes-code** [quickjs-ng/quickjs#751]
I'm writing code to sort of fake inheritance from C++ to JS using a C++ wrapper I'm writing. But when the JS code calls `super.someFunction()` in a function that was overridden, there's no way to get the `this` of the class that was invoked.

**Comment by bnoordhuis** [comment]
Your description is not super clear. Can you post example code?

**Comment by Oliver-makes-code** [comment]
After further investigation, this seems to be user error. I wasn't passing `this` properly.
Though is there a way to check if a function was called though `super`?

**Comment by bnoordhuis** [comment]
If your question is: can a C function distinguish between `super.cfunc()` and `this.cfunc()` calls? No.

If your question is: can a C function distinguish between `super.cfunc()` and `cfunc()` calls? Yes, check if `this_val` is an object (and, optionally, the expected type of object.)
