### ISSUE TITLE
Expose predefined class_ids for efficient lookup?

### ISSUE THREAD

**Issue by richarddd** [quickjs-ng/quickjs#758]
When checking if an object is an instance of a an added intrinsic object such a uint8 typed array it would be useful to check the class id directly.

We can access the class id via JS_GetClassID but we can't compare with anything as the already defined tags are stored in an private unnamed enum.

This is currently rather brittle in `rquckjs` as typed arrays are checked by looking at the constructor name in global scope and calling `qjs::JS_IsInstanceOf`

**Comment by saghul** [comment]
So basically have a way to know if the class ID is in this enum: https://github.com/quickjs-ng/quickjs/blob/374915ad0c38d8a948d492c6d4a735f320339a63/quickjs.c#L119

I guess the simplest way would be to add some `int JS_IsIntrinsic(JSClassID class_id)` perhaps?

**Comment by richarddd** [comment]
Kind of, or rather:
```c
if(classId == JS_CLASS_INT32_ARRAY){

}
```

**Comment by saghul** [comment]
We could perhaps expose the whole enum... I guess it should be harmless. WDYT @bnoordhuis ?

**Comment by chqrlie** [comment]
> We could perhaps expose the whole enum... I guess it should be harmless. WDYT @bnoordhuis ?

The enum is already exposed in **bellard/quickjs** for `JS_NewTypedArray`

**Comment by saghul** [comment]
Not for all class types, which I guess is what @richarddd also needs?

**Comment by richarddd** [comment]
Yeah why not? @chqrlie yes, but that won't help as i wont know the offset here `class id` used here:
https://github.com/bellard/quickjs/blob/6e2e68fd0896957f92eb6c242a2e048c1ef3cae0/quickjs.c#L53441C39-L53441C60

So simply expose the entire enum would be preferable and class type checks would be a breeze for integrators :)

**Comment by bnoordhuis** [comment]
> We could perhaps expose the whole enum... I guess it should be harmless. WDYT @bnoordhuis ?

ABI pitfall: the enum ends with `JS_CLASS_INIT_COUNT`. How do we add new classes without breaking ABI?

**Comment by saghul** [comment]
With a fast moving ecosystem like JS does it make sense to make many promises (yeah, pun intended) about ABI compatibility? Just thinking out loud.

**Comment by bnoordhuis** [comment]
I'd like to see libquickjs show up in distros someday, also because that makes downstream projects' lives easier, so I'd rather not paint ourselves into a corner too quickly, ABI-wise.

Adding API functions is fair game though. For the use case @richarddd mentions, sounds like it should be enough to have `JS_IsTypedArray()`, `JS_IsUint8Array()`, etc.?

**Comment by richarddd** [comment]
> Adding API functions is fair game though. For the use case @richarddd mentions, sounds like it should be enough to have `JS_IsTypedArray()`, `JS_IsUint8Array()`, etc.?

I think that works if we can expose one method for each typed array type.

My issues one can be solved by adding `JS_NewTypedArray` from upstream and `JS_IsTypedArray()`

For reference, here are are where I need to make changes.
https://github.com/DelSkayn/rquickjs/blob/master/core/src/value/typed_array.rs#L154-L164
https://github.com/DelSkayn/rquickjs/blob/master/core/src/value/typed_array.rs#L193-L200
https://github.com/DelSkayn/rquickjs/blob/master/core/src/value/typed_array.rs#L311-L318
https://github.com/DelSkayn/rquickjs/blob/master/core/src/value/typed_array.rs#L154-L164

**Comment by Sytten** [comment]
To revive a bit this conversation, we actually need the class ID too in the serde serializer/deserializer like
https://github.com/rquickjs/rquickjs-serde/blob/62d44b26efbd11b37058cb3697391a9faa23b4fa/src/de.rs#L214-L215
I didnt write the original code for this, so there might be a better way to do this (for example I am not sure I fully understand the difference between a tag and a class id). For now they are hardcoded in Rust which is not good.
Maybe we need `JS_GetBoolClassID`?

**Comment by bnoordhuis** [comment]
`JS_IsBigInt()` is what you {c,sh}ould be using on that line you link to, right?

**Comment by Sytten** [comment]
Maybe? I am not exactly sure why the original author did both a tag check and a class ID check. I have the feeling that it might be for another edge case. Is it possible that a given value would have a class id of bool/number/bigint but not the tag?

**Comment by bnoordhuis** [comment]
It's trying to handle both primitive bigints and BigInt objects (`42n` vs. `Object(42n)`.) I can't tell from looking at the code whether it's sensible to do so, and whether it does so in a sensible manner.

`JS_IsBigInt()` reports true for primitive bigints, not BigInt objects. The latter aren't really bigints, they're objects with an internal field that happens to be a bigint (same as with String/Number/etc. objects.)

If you really need to distinguish between the two, we could add `JS_IsBigIntObject(JSContext *ctx, JSValue v)` and others, although you can already do that with something like this (error handling elided):
```c
JSValue val = /* ... */;
JSValue global = JS_GetGlobalObject(ctx);
JSValue klass = JS_GetPropertyStr(ctx, global, "BigInt"); // see note
int result = JS_IsInstanceOf(ctx, val, klass); // -1, false, true
```
You can likewise:
- create BigInt objects by looking up and calling `Object`
- get the value of the internal field by invoking the object's `.valueOf` method

(Also applies to String/Number/etc.)

note: `globalThis.BigInt` is mutable by user JS code so you may want to look it up and cache before first use; or only (de)serialize into pristine contexts.

**Comment by Sytten** [comment]
@bnoordhuis Thanks for the detailed answer, it makes more sense now.
The BigInt is probably not a good example but the bool vs Bool is a good one:
```rust
  if self.value.is_bool() {
            return visitor.visit_bool(self.value.as_bool().expect("value to be boolean"));
        }

        if get_class_id(&self.value) == ClassId::Bool as u32 {
            let value_of = get_valueof(&self.value);
            if let Some(f) = value_of {
                let v = f.call((This(self.value.clone()),))?;
                return visitor.visit_bool(v);
            }
        }
```
Essentially when it's a primitive it basically does:
```rust
#[inline]
pub unsafe fn JS_VALUE_GET_BOOL(v: JSValue) -> bool {
    v.u.int32 != 0
}
```
And if it's a Bool object then it calls `valueOf`.

The methods `JS_IsXObject` would be perfect, though at this point you might want to expose a little bit of the internal class ID enum like you did with `JSTypedArrayEnum`. I think the initial concern was about not exposing `JS_CLASS_INIT_COUNT`, but I feel like that could be another enum with just the items you guys want to stabilize (and honestly it doesn't really have to be stable since we can read them at runtime).

**Comment by bnoordhuis** [comment]
> though at this point you might want to expose a little bit of the internal class ID enum like you did with JSTypedArrayEnum

I don't really want to do that because (speaking from prior experience) it's too easy to paint yourself into a corner once you start exposing implementation details, and we do want to release a 1.0 with a stable API and ABI someday.

JSTypedArrayEnum doesn't really have that issue because it's pretty much frozen; at best, it gets extended with new types, but existing ones won't disappear, get rearranged, etc.
