### ISSUE TITLE
Reporting external memory pressure

### ISSUE THREAD

**Issue by ammarahm-ed** [quickjs-ng/quickjs#759]
Is it possible in quickjs to report external memory pressure so GC can trigger more often?

**Comment by saghul** [comment]
You could either trigger GC manually, or change the threshold. Would that work?

**Comment by bnoordhuis** [comment]
Saúl's speaking of JS_SetGCThreshold, the memory limit that triggers the next GC sweep. It's set after every sweep to 1.5x current memory usage, so if you want the GC to run sooner, do something like this:
```c
void adjust_gc_threshold(JSRuntime *rt, int64_t size) {
    static size_t old;
    size_t cur = JS_GetGCThreshold(rt);
    if (cur != old && size < 0) return; // don't update, changed after GC
    int64_t new = cur - size;
    if (new < 0) new = 0;
    JS_SetGCThreshold(rt, new);
    old = new;
}
```
Using `int64_t` means you can adjust in both directions, i.e.:
```c
int64_t n = 1<<20;
void *p = malloc(n);
adjust_gc_threshold(rt, n);
// ...
free(p);
adjust_gc_threshold(rt, -n);
```

**Comment by ammarahm-ed** [comment]
Thanks! this clears it up.
