### ISSUE TITLE
Add option for module imports to not error when an import doesn't have an object

### ISSUE THREAD

**Issue by Oliver-makes-code** [quickjs-ng/quickjs#762]
Hi! In my engine, I'm using a Typescript stripper, which strips Typescript-only syntax, turning it into valid Javascript (I'm using https://github.com/swc-project/swc/tree/main/crates/swc_fast_ts_strip specifically)
But the Typescript stripper only has access to the current file it's stripping, and thus is unable to tell type imports from non-type imports
```ts
import { SomeType } from "./some_script.ts"
// is virtually indistinguishable from
import { someValue } from "./some_script.ts" 
```
Since the stripper is unable to tell if it's a type or not, it leaves it in the import statement.
This causes an error to be thrown, if that identifier doesn't have some real value backing it.

My proposal to fix this, is to add an option that, if an import isn't found, it gracefully handles it (maybe by setting the value to `undefined`, or something like that?)

Or maybe the fallback value can be set by the user?
```c
JS_SetFallbackImport(ctx, JS_UNDEFINED);
```
You could have it so that if the fallback value defaults to `JS_UNINITIALIZED`, then if it's not `JS_UNINITIALIZED`, it's treated as having found that import.

**Comment by saghul** [comment]
The use case feels super narrow and very problematic as a general API.

Is there nothing that can strip types and remove imports? How about esbuild?

**Comment by bnoordhuis** [comment]
I agree with what Saúl says, and also, we don't want to be in the business of language extensions. This is something you'll need to handle on your end.
