### ISSUE TITLE
Question about the removal of JSRefCountHeader 

### ISSUE THREAD

**Issue by andrieshiemstra** [quickjs-ng/quickjs#766]
Since https://github.com/quickjs-ng/quickjs/pull/570 JSRefCountHeader is no longer exposed, while i agree that api wise that is a good thing I kinda liked to use to check the ref count in my tests.

Is there another way to see the current refcount of a JSValue?

**Comment by bnoordhuis** [comment]
Not exposed at the moment, no, but refcount errors hit an assert in JS_FreeRuntime in debug builds.

**Comment by andrieshiemstra** [comment]
Ok, thanks for the reply!

**Comment by bnoordhuis** [comment]
Forgot to mention, another debug tool is calling JS_SetDumpFlags with `0x4000|0x8000` (object leaks + atom leaks); it's the `-D` flag to qjs.

edit: grep quickjs.c for `DUMP_LEAKS` to find all flags.

**Comment by andrieshiemstra** [comment]
Thank for the extra info, I'll look into that. 

For now I just disabled my ref-count checks when using quickjs-ng and only do it when using the original Bellard version, most test cases are remnants from when I was implementing the early versions of my library and didn't exactly when to dup&free so it shouldn't have to much effect.

Thank for you great efforts with this project!
