### ISSUE TITLE
JS_DetectModule gives false positive on dynamic imports

### ISSUE THREAD

**Issue by andrieshiemstra** [quickjs-ng/quickjs#767]
.e.g a script like ```import('foo.js').then((a) = {});``` now gives true in JS_DetectModule.

In 0.6.1 it was (correctly) false

**Comment by andrieshiemstra** [comment]
hmm, actually it's worse.. pretty much every string I throw at it returns true?

**Comment by bnoordhuis** [comment]
See https://github.com/quickjs-ng/quickjs/pull/610#issuecomment-2424209322 but basically: working as expected, just differently than before.

**Comment by andrieshiemstra** [comment]
Thanks.
